;;; Complete natural CLEAR-FILL-MAP / WRITE-LIST-TO-FILL-MAP map boundaries.
;;; Coordinates use natural X/Y calls; frame slots use the natural CFRAME result.
;;; No additional application reader calls, map writes or fill calls.
(in-package :cl-user)

(unless (boundp 'aaron-boundary-map-capture-loaded)
  (set 'aaron-boundary-map-capture-loaded t)
  (let* ((owner (find-package "COMMON-GRAPHICS-USER"))
         (report (open "C:\\temp\\aaron-boundary-map.txt"
                       :direction :output :if-exists :supersede
                       :if-does-not-exist :create))
         (targets '("CLEAR-FILL-MAP" "WRITE-LIST-TO-FILL-MAP"))
         (calls 0) (parents 0) (errors 0) (aborts 0) (overflow nil)
         (cells-total 0) (runs-total 0) (points-total 0) (rng-checks 0)
         (reader-total 0) (slot-checks 0) (stack nil) (parent-stack nil) (current nil)
         (counts (make-hash-table :test #'equal)))
    (labels
        ((emit (control &rest args)
           (when report
             (handler-case
                 (let ((*print-length* nil) (*print-level* nil)
                       (*print-pretty* nil) (*print-circle* nil)
                       (*print-readably* nil))
                   (apply #'format report control args) (terpri report))
               (condition () (incf errors)))))
         (problem (id phase condition)
           (incf errors)
           (emit "ERROR id=~D phase=~S type=~S" id phase
                 (format nil "~S" (type-of condition))))
         (limit (kind amount)
           (setf overflow t)
           (emit "OVERFLOW kind=~S amount=~D" kind amount)
           (error "Boundary map observation cap"))
         (global (name)
           (let ((symbol (find-symbol name owner)))
             (unless (and symbol (boundp symbol)) (error "Missing map binding"))
             (symbol-value symbol)))
         (point-order (value table)
           (let ((rest value) (order nil) (count 0)
                 (seen (make-hash-table :test #'eq)))
             (do () ((not (consp rest)))
               (when (gethash rest seen) (error "Cyclic input list"))
               (setf (gethash rest seen) t)
               (when (>= count 10000) (limit :list-points count))
               (let* ((point (car rest)) (record (gethash point table)))
                 (unless record
                   (setf record
                         (list :id (1+ (hash-table-count table))
                               :type (format nil "~S" (type-of point))
                               :x nil :y nil :x-calls 0 :y-calls 0)
                         (gethash point table) record))
                 (push (getf record :id) order))
               (incf count) (setf rest (cdr rest)))
             (unless (null rest) (error "Improper input list"))
             (nreverse order)))
         (make-context (id name args)
           (unless (= (length args) 2) (error "Unexpected target arguments"))
           (let ((context (list :id id :name name :frame nil :frame-calls 0 :slots nil
                                :points (make-hash-table :test #'eq)
                                :order nil :list nil)))
             (if (string= name "WRITE-LIST-TO-FILL-MAP")
                 (progn
                   (unless (and (integerp (second args)) (<= 0 (second args) 15))
                     (error "Non-four-bit writer value"))
                   (setf (getf context :list) (first args)
                         (getf context :order)
                         (point-order (first args) (getf context :points)))
                   (incf points-total (length (getf context :order)))
                   (when (> points-total 1000000) (limit :total-points points-total)))
               (unless (every #'integerp args) (error "Noninteger clear indices")))
             context))
         (map-snapshot ()
           (let ((map (global "FILL-MAP")))
             (unless (and (arrayp map) (= (array-rank map) 2)
                          (equal (array-element-type map) '(unsigned-byte 4)))
               (error "Expected rank-two four-bit map"))
             (let* ((dimensions (array-dimensions map))
                    (width (first dimensions)) (height (second dimensions))
                    (cells (* width height)) (rows nil) (runs 0))
               (unless (and (> width 0) (> height 0) (<= cells 153600))
                 (limit :map-cells cells))
               (when (> (+ cells-total cells) 60000000)
                 (limit :total-cells (+ cells-total cells)))
               (dotimes (y height)
                 (let ((row nil) (value nil) (count 0))
                   (dotimes (x width)
                     (let ((next (aref map x y)))
                       (if (and (> count 0) (= value next))
                           (incf count)
                         (progn
                           (when (> count 0) (push (list value count) row) (incf runs))
                           (setf value next count 1)))))
                   (when (> count 0) (push (list value count) row) (incf runs))
                   (push (list y :runs (nreverse row)) rows)))
               (incf cells-total cells) (incf runs-total runs)
               (when (> runs-total 2000000) (limit :map-runs runs-total))
               (list (list :type (format nil "~S" (type-of map))
                           :dimensions dimensions :element-type (array-element-type map)
                           :cells cells :covered cells :runs runs :complete t
                           :rows (nreverse rows)) map))))
         (safe-map (id phase)
           (handler-case
               (let* ((preview (aaron-random-state-preview)) (result (map-snapshot)))
                 (unless (and (eq (car preview) :random-100-1)
                              (equal preview (aaron-random-state-preview)))
                   (error "Snapshot changed copied random-state preview"))
                 (incf rng-checks) result)
             (condition (condition) (problem id phase condition) (list nil nil))))
         (frame-slots (frame)
           (let ((preview (aaron-random-state-preview)) (record nil))
             (dolist (name '("LX" "RX" "LY" "TY"))
               (let* ((symbol (find-symbol name owner)) (value (slot-value frame symbol)))
                 (unless (integerp value) (error "Noninteger frame slot"))
                 (setf record (append record (list name value)))))
             (unless (and (eq (car preview) :random-100-1)
                          (equal preview (aaron-random-state-preview)))
               (error "Frame slot observation changed copied random-state preview"))
             (incf slot-checks) record))
         (record-reader (name args values)
           (when current
             (unless (and (= (length args) 1) (= (length values) 1))
               (error "Unexpected natural reader signature"))
             (cond
               ((and (string= (getf current :name) "CLEAR-FILL-MAP") (string= name "CFRAME"))
                (incf reader-total)
                (when (> reader-total 5000000) (limit :readers reader-total))
                (when (and (> (getf current :frame-calls) 0)
                           (not (eq (getf current :frame) (car values))))
                  (error "Natural frame identity changed"))
                (when (= (getf current :frame-calls) 0)
                  (setf (getf current :slots) (frame-slots (car values))))
                (setf (getf current :frame) (car values))
                (incf (getf current :frame-calls)))
               ((and (string= (getf current :name) "WRITE-LIST-TO-FILL-MAP")
                     (member name '("X" "Y") :test #'string=))
                (incf reader-total)
                (when (> reader-total 5000000) (limit :readers reader-total))
                (let* ((record (gethash (car args) (getf current :points)))
                       (value (car values))
                       (key (if (string= name "X") :x :y))
                       (count-key (if (string= name "X") :x-calls :y-calls)))
                  (unless (and record (integerp value)) (error "Natural point reader mismatch"))
                  (when (and (> (getf record count-key) 0) (/= (getf record key) value))
                    (error "Natural coordinate changed"))
                  (setf (getf record key) value) (incf (getf record count-key)))))))
         (reader-record (context)
           (if (string= (getf context :name) "CLEAR-FILL-MAP")
               (let ((after (frame-slots (getf context :frame))))
                 (list :type (format nil "~S" (type-of (getf context :frame)))
                       :frame-calls (getf context :frame-calls)
                       :source "SLOT-VALUE" :before (getf context :slots) :after after))
             (let ((records nil))
               (maphash (lambda (point record) (declare (ignore point))
                          (push (list (getf record :id) (getf record :type)
                                      (getf record :x) (getf record :y)
                                      (getf record :x-calls) (getf record :y-calls)) records))
                        (getf context :points))
               (list :points (sort records #'< :key #'car)
                     :order-equal (equal (getf context :order)
                                         (point-order (getf context :list) (getf context :points)))))))
         (install-reader (name)
           (let* ((symbol (find-symbol name owner)) (original (symbol-function symbol)))
             (emit "INSTALL name=~S type=~S" name (format nil "~S" (type-of original)))
             (setf (symbol-function symbol)
                   (lambda (&rest args)
                     (if (or (null current) overflow)
                         (apply original args)
                       (multiple-value-call
                           (lambda (&rest values)
                             (handler-case (record-reader name args values)
                               (condition (condition) (problem (getf current :id) name condition)))
                             (values-list values))
                         (apply original args)))))))
         (install-target (name)
           (let* ((symbol (find-symbol name owner)) (original (symbol-function symbol)))
             (emit "INSTALL name=~S type=~S" name (format nil "~S" (type-of original)))
             (setf (symbol-function symbol)
                   (lambda (&rest args)
                     (if (or (null report) overflow (>= calls 500))
                         (progn
                           (when (and report (not overflow))
                             (setf overflow t) (emit "OVERFLOW kind=:CALLS amount=~D" calls))
                           (apply original args))
                       (let* ((id (incf calls)) (prior current) (completed nil)
                              (context (handler-case (make-context id name args)
                                         (condition (condition) (problem id :arguments condition) nil)))
                              (before (safe-map id :before)))
                         (incf (gethash name counts 0))
                         (push id stack)
                         (emit "CALL id=~D parent=~D name=~S args=~S before=~S"
                               id (or (car parent-stack) 0) name
                               (if (string= name "WRITE-LIST-TO-FILL-MAP")
                                   (list :length (length (getf context :order)) :value (second args)
                                         :order (getf context :order)) args)
                               (first before))
                         (setf current context)
                         (unwind-protect
                             (multiple-value-call
                                 (lambda (&rest values)
                                   (setf completed t)
                                   (let ((after (safe-map id :after)))
                                     (handler-case
                                         (emit "RETURN id=~D values=~S readers=~S after=~S map-eq-entry=~S"
                                               id values (reader-record context) (first after)
                                               (eq (second before) (second after)))
                                       (condition (condition) (problem id :return condition))))
                                   (values-list values))
                               (apply original args))
                           (unless completed (incf aborts) (emit "ABORT id=~D" id))
                           (pop stack) (setf current prior))))))))
         (install-parent (name)
           (let* ((symbol (find-symbol name owner)) (original (symbol-function symbol)))
             (emit "INSTALL name=~S type=~S" name (format nil "~S" (type-of original)))
             (setf (symbol-function symbol)
                   (lambda (&rest args)
                     (if (or (null report) overflow (>= parents 1000))
                         (progn
                           (when (and report (not overflow))
                             (setf overflow t) (emit "OVERFLOW kind=:PARENTS amount=~D" parents))
                           (apply original args))
                       (let ((id (incf parents)) (completed nil))
                         (handler-case
                             (emit "PARENT id=~D parent=~D name=~S args=~S" id
                                   (or (car parent-stack) 0) name
                                   (if (string= name "MY-FILL")
                                       (list (if (symbolp (first args)) (symbol-name (first args))
                                               (format nil "~S" (type-of (first args))))
                                             (second args) (third args)) args))
                           (condition (condition) (problem id :parent-arguments condition)))
                         (push id parent-stack)
                         (unwind-protect
                             (multiple-value-prog1 (apply original args)
                               (setf completed t) (emit "END-PARENT id=~D" id))
                           (unless completed (incf aborts) (emit "ABORT-PARENT id=~D" id))
                           (pop parent-stack))))))))
         (finish (status)
           (dolist (name targets) (emit "TOTAL name=~S calls=~D" name (gethash name counts 0)))
           (emit "COMPLETE main=~S calls=~D parents=~D points=~D cells=~D runs=~D readers=~D rng-checks=~D slot-checks=~D errors=~D aborts=~D overflow=~S depth=~D parent-depth=~D"
                 status calls parents points-total cells-total runs-total reader-total
                 rng-checks slot-checks errors aborts overflow (length stack) (length parent-stack))
           (emit "END boundary-map v2")
           (when report (finish-output report) (close report) (setf report nil))))
      (emit "BEGIN boundary-map v2")
      (emit "CAPS calls=500 parents=1000 list-points=10000 total-points=1000000 map-cells=153600 total-cells=60000000 map-runs=2000000 readers=5000000")
      (dolist (name '("CFRAME" "X" "Y")) (install-reader name))
      (dolist (name targets) (install-target name))
      (dolist (name '("MY-FILL" "BRUSH-FILL-SUBPART")) (install-parent name))
      (let* ((symbol (find-symbol "MAIN" owner)) (original (symbol-function symbol)))
        (emit "INSTALL name=~S type=~S" "MAIN" (format nil "~S" (type-of original)))
        (setf (symbol-function symbol)
              (lambda (&rest args)
                (let ((completed nil))
                  (unwind-protect
                      (multiple-value-prog1 (apply original args)
                        (setf completed t) (finish :normal))
                    (unless completed (finish :aborted)))))))
      (emit "READY"))))
