;;; Read-only PAINT-BRUSH class probe.  This follows the startup census:
;;; ALL-BRUSHES is a six-element list, while BRUSH and FILL-MAP are not bound
;;; at the direct-screensaver checkpoint.  No accessor, drawing, or fill
;;; routine runs until the class shape is known.
(in-package :cl-user)
(unless (boundp 'aaron-brush-accessors-loaded)
  (set 'aaron-brush-accessors-loaded t)
  (with-open-file (report "C:\\temp\\aaron-brush-accessors.txt"
                          :direction :output :if-exists :supersede
                          :if-does-not-exist :create)
    (let ((*print-length* 16) (*print-level* 10) (*print-pretty* nil)
          (user (find-package "COMMON-GRAPHICS-USER"))
          (graphics (find-package "COMMON-GRAPHICS")))
      (labels ((shape (value &optional (depth 0))
                 (cond
                   ((numberp value) (list :number value))
                   ((symbolp value)
                    (list :symbol (and (symbol-package value)
                                       (package-name (symbol-package value)))
                          (symbol-name value)))
                   ((stringp value)
                    (list :string (length value)
                          (subseq value 0 (min 120 (length value)))))
                   ((arrayp value)
                    (let ((samples nil) (total (array-total-size value)))
                      (dotimes (index (min total 8))
                        (push (shape (row-major-aref value index) (1+ depth))
                              samples))
                      (list :array (type-of value)
                            :rank (array-rank value)
                            :dimensions (array-dimensions value)
                            :element-type (array-element-type value)
                            :samples (nreverse samples))))
                   ((and (consp value) (< depth 5))
                    (list :cons (shape (car value) (1+ depth))
                          (shape (cdr value) (1+ depth))))
                   (t (list :type (type-of value)))))
               (find-in (package name)
                 (and package (find-symbol name package)))
               (helper (name)
                 (let ((found nil))
                   (do-all-symbols (symbol)
                     (when (and (null found) (string= name (symbol-name symbol))
                                (fboundp symbol))
                       (setf found symbol)))
                   found))
               (class-report (object)
                 (format report "BEFORE-CLASS-OF~%")
                 (finish-output report)
                 (handler-case
                     (let* ((class (class-of object))
                            (class-name-fn (find-in (find-package "CLOS")
                                                    "CLASS-NAME"))
                            (class-slots-fn (helper "CLASS-SLOTS"))
                            (slot-name-fn (helper "SLOT-DEFINITION-NAME")))
                       (format report "CLASS-OF ~S~%" (type-of class))
                       (when (and class-name-fn (fboundp class-name-fn))
                         (format report "CLASS-NAME ~S~%"
                                 (funcall (symbol-function class-name-fn) class)))
                       (format report "CLASS-SLOTS-HELPER ~S~%"
                               (shape class-slots-fn))
                       (when (and class-slots-fn slot-name-fn)
                         (handler-case
                             (let ((slots (funcall class-slots-fn class)))
                               (format report "SLOT-COUNT ~D~%" (length slots))
                               (dolist (slot slots)
                                 (handler-case
                                     (format report "SLOT ~S~%"
                                             (shape (funcall slot-name-fn slot)))
                                   (error (problem)
                                     (format report "SLOT-ERROR ~S~%"
                                             (type-of problem)))))
                               (finish-output report))
                           (error (problem)
                             (format report "SLOTS-ERROR ~S~%"
                                     (type-of problem))))))
                   (error (problem)
                     (format report "CLASS-ERROR ~S~%" (type-of problem))))
                 (finish-output report)))
        (format report "BEGIN brush-accessors~%")
        (format report "INTERVENTION READ-ONLY-PAINT-BRUSH-ACCESSORS~%")
        (let ((all-symbol (find-in user "ALL-BRUSHES"))
              (boundary-symbol (find-in user "BOUNDARY-VALUE")))
          (format report "ALL-BRUSHES bound=~S~%"
                  (and all-symbol (boundp all-symbol)))
          (when (and all-symbol (boundp all-symbol))
            (format report "ALL-BRUSHES-SHAPE ~S~%"
                    (shape (symbol-value all-symbol))))
          (format report "BOUNDARY-VALUE bound=~S~%"
                  (and boundary-symbol (boundp boundary-symbol)))
          (when (and boundary-symbol (boundp boundary-symbol))
            (format report "BOUNDARY-VALUE-SHAPE ~S~%"
                    (shape (symbol-value boundary-symbol))))
          (finish-output report)
          (when (and all-symbol (boundp all-symbol))
            (let ((brushes (symbol-value all-symbol)))
              (when (consp brushes)
                (format report "BRUSH index=0 shape=~S~%" (shape (car brushes)))
                (finish-output report)
                (class-report (car brushes)))))
        (format report "END brush-accessors~%")
        (finish-output report))))))
