;;; Read-only PAINT-BRUSH accessor probe.  This follows the startup census:
;;; ALL-BRUSHES is a six-element list, while BRUSH and FILL-MAP are not bound
;;; at the direct-screensaver checkpoint.  No drawing or fill routine runs.
(in-package :cl-user)
(unless (boundp 'aaron-brush-accessors-loaded)
  (set 'aaron-brush-accessors-loaded t)
  (with-open-file (report "C:\\temp\\aaron-brush-accessors.txt"
                          :direction :output :if-exists :supersede
                          :if-does-not-exist :create)
    (let ((*print-length* 16) (*print-level* 10) (*print-pretty* nil)
          (user (find-package "COMMON-GRAPHICS-USER"))
          (graphics (find-package "COMMON-GRAPHICS")))
      (labels ((shape (value &optional (depth 0))
                 (cond
                   ((numberp value) (list :number value))
                   ((symbolp value)
                    (list :symbol (and (symbol-package value)
                                       (package-name (symbol-package value)))
                          (symbol-name value)))
                   ((stringp value)
                    (list :string (length value)
                          (subseq value 0 (min 120 (length value)))))
                   ((arrayp value)
                    (let ((samples nil) (total (array-total-size value)))
                      (dotimes (index (min total 8))
                        (push (shape (row-major-aref value index) (1+ depth))
                              samples))
                      (list :array (type-of value)
                            :rank (array-rank value)
                            :dimensions (array-dimensions value)
                            :element-type (array-element-type value)
                            :samples (nreverse samples))))
                   ((and (consp value) (< depth 5))
                    (list :cons (shape (car value) (1+ depth))
                          (shape (cdr value) (1+ depth))))
                   (t (list :type (type-of value)))))
               (find-in (package name)
                 (and package (find-symbol name package)))
               (accessor (name package object)
                 (let ((symbol (find-in package name)))
                   (format report "ACCESSOR ~S package=~S fbound=~S~%"
                           name (and package (package-name package))
                           (and symbol (fboundp symbol)))
                   (finish-output report)
                   (when (and symbol (fboundp symbol))
                     (handler-case
                         (format report "RESULT ~S~%"
                                 (shape (funcall (symbol-function symbol) object)))
                       (error (problem)
                         (format report "ERROR ~S~%" (type-of problem))))
                     (finish-output report)))))
        (format report "BEGIN brush-accessors~%")
        (format report "INTERVENTION READ-ONLY-PAINT-BRUSH-ACCESSORS~%")
        (let ((all-symbol (find-in user "ALL-BRUSHES"))
              (boundary-symbol (find-in user "BOUNDARY-VALUE")))
          (format report "ALL-BRUSHES bound=~S~%"
                  (and all-symbol (boundp all-symbol)))
          (when (and all-symbol (boundp all-symbol))
            (format report "ALL-BRUSHES-SHAPE ~S~%"
                    (shape (symbol-value all-symbol))))
          (format report "BOUNDARY-VALUE bound=~S~%"
                  (and boundary-symbol (boundp boundary-symbol)))
          (when (and boundary-symbol (boundp boundary-symbol))
            (format report "BOUNDARY-VALUE-SHAPE ~S~%"
                    (shape (symbol-value boundary-symbol))))
          (finish-output report)
          (dolist (entry '(("WIDTH" "COMMON-GRAPHICS")
                           ("PERIM" "COMMON-GRAPHICS-USER")
                           ("CORE" "COMMON-GRAPHICS-USER")
                           ("IN-SUB-FRAME" "COMMON-GRAPHICS-USER")))
            (let* ((name (car entry))
                   (package (find-package (cadr entry)))
                   (symbol (find-in package name)))
              (format report "FUNCTION ~S package=~S fbound=~S type=~S~%"
                      name (and package (package-name package))
                      (and symbol (fboundp symbol))
                      (and symbol (fboundp symbol)
                           (type-of (symbol-function symbol)))))
            (finish-output report))
          (when (and all-symbol (boundp all-symbol))
            (let ((brushes (symbol-value all-symbol)) (index 0))
              (do ((rest brushes (cdr rest)))
                  ((or (null rest) (>= index 8)))
                (let ((brush (car rest)))
                  (format report "BRUSH index=~D shape=~S~%" index (shape brush))
                  (finish-output report)
                  (accessor "WIDTH" graphics brush)
                  (accessor "PERIM" user brush)
                  (accessor "CORE" user brush)
                  (accessor "IN-SUB-FRAME" user brush))
                (incf index)))))
        (format report "END brush-accessors~%")
        (finish-output report)))))
