;;; Natural plan/list/form/frame links and row/MAX inputs. No extra getters.
(in-package :cl-user)

(unless (boundp 'aaron-brush-fill-preparation-loaded)
  (set 'aaron-brush-fill-preparation-loaded t)
  (let* ((owner (find-package "COMMON-GRAPHICS-USER"))
         (report (open "C:\\temp\\aaron-brush-fill-preparation.txt" :direction :output
                       :if-exists :supersede :if-does-not-exist :create))
         (ids (make-hash-table :test #'eq)) (next-id 0) (parents 0) (calls 0)
         (checks 0) (errors 0) (aborts 0) (overflow nil) (active nil) (busy 0)
         (last-frame nil) (last-form nil) (last-patch nil) (last-scan nil))
    (labels
        ((emit (control &rest args)
           (when report
             (handler-case
                 (let ((*print-length* nil) (*print-level* nil) (*print-pretty* nil)
                       (*print-circle* nil) (*print-readably* nil))
                   (apply #'format report control args) (terpri report))
               (condition () (incf errors)))))
         (problem (phase condition)
           (incf errors) (emit "ERROR phase=~S type=~S message=~S" phase
                              (format nil "~S" (type-of condition)) (format nil "~A" condition)))
         (global (name)
           (let ((symbol (find-symbol name owner)))
             (unless (and symbol (boundp symbol)) (error "Missing binding ~A" name))
             (symbol-value symbol)))
         (object-id (object)
           (if (null object) 0
             (or (gethash object ids)
                 (let ((id (incf next-id)))
                   (when (> next-id 10000) (setf overflow t) (error "Object identity cap"))
                   (setf (gethash object ids) id)
                   (emit "OBJECT id=~D type=~S" id (format nil "~S" (type-of object))) id))))
         (members (value)
           (let ((rest value) (result nil) (seen (make-hash-table :test #'eq)) (count 0))
             (do () ((not (consp rest)))
               (when (or (gethash rest seen) (>= count 1000)) (error "Improper/capped plan list"))
               (setf (gethash rest seen) t) (push (object-id (car rest)) result)
               (incf count) (setf rest (cdr rest)))
             (unless (null rest) (error "Improper plan list")) (nreverse result)))
         (slot (object name)
           (let ((value (slot-value object (find-symbol name owner))))
             (unless (integerp value) (error "Noninteger slot ~A" name)) value))
         (frame (object)
           (when object (list (object-id object) (slot object "LX") (slot object "RX")
                             (slot object "LY") (slot object "TY"))))
         (point (object)
           (when object (list (object-id object) (slot object "X") (slot object "Y") (slot object "Z"))))
         (snapshot (phase thunk)
           (handler-case
               (let* ((preview (aaron-random-state-preview)) (result (funcall thunk)))
                 (unless (and (eq (car preview) :random-100-1)
                              (equal preview (aaron-random-state-preview)))
                   (error "Snapshot changed copied random preview"))
                 (incf checks) result)
             (condition (condition) (problem phase condition) nil)))
         (before (name args)
           (cond ((or (string= name "SCRIPT") (string= name "CFLIST") (string= name "CFRAME"))
                  (unless (= (length args) 1) (error "Unsupported reader arity"))
                  (list :object (object-id (car args)) :mplan-eq (eq (car args) (global "MPLAN"))))
                 ((string= name "SCAN-ROW")
                  (list :args args :form (object-id last-form) :frame (frame last-frame) :patch-read last-patch))
                 (t (list :start (point (first args)) :max (second args) :p (third args)
                          :form (object-id last-form) :frame (frame last-frame) :scan-eq (eq (first args) last-scan)))))
         (after (name args values)
           (unless (= (length values) 1) (error "Unsupported natural arity"))
           (let ((value (car values)))
             (cond ((or (string= name "SCRIPT") (string= name "CFLIST"))
                    (list :object (object-id value) :members (members value)))
                   ((string= name "CFRAME")
                    (setf last-form (car args) last-frame value)
                    (list :form (object-id last-form) :frame (frame value)))
                   ((string= name "SCAN-ROW")
                    (setf last-scan value) (list :point (point value)))
                   (t (list :start (point (car args)) :nil (null value))))))
         (install (name)
           (let* ((symbol (find-symbol name owner)) (original (symbol-function symbol)))
             (emit "INSTALL name=~S type=~S" name (format nil "~S" (type-of original)))
             (setf (symbol-function symbol)
                   (lambda (&rest args)
                     (if (or (null report) (null active) (> busy 0)) (apply original args)
                       (let ((id (incf calls)) (completed nil))
                         (when (> calls 60000) (setf overflow t) (error "Preparation call cap"))
                         (emit "CALL id=~D parent=~D name=~S before=~S" id active name
                               (snapshot :before (lambda () (before name args))))
                         (unwind-protect
                             (multiple-value-call
                                 (lambda (&rest values)
                                   (setf completed t)
                                   (emit "RETURN id=~D after=~S" id
                                         (snapshot :after (lambda () (after name args values))))
                                   (values-list values))
                               (apply original args))
                           (unless completed (incf aborts) (emit "ABORT id=~D" id)))))))))
         (exclude (name)
           (let* ((symbol (find-symbol name owner)) (original (symbol-function symbol)))
             (emit "EXCLUDE name=~S type=~S" name (format nil "~S" (type-of original)))
             (setf (symbol-function symbol)
                   (lambda (&rest args)
                     (incf busy) (unwind-protect (apply original args) (decf busy))))))
         (finish (status)
           (emit "COMPLETE main=~S parents=~D calls=~D objects=~D checks=~D errors=~D aborts=~D overflow=~S active=~S busy=~D"
                 status parents calls next-id checks errors aborts overflow active busy)
           (emit "END brush-fill-preparation v2") (finish-output report) (close report) (setf report nil)))
      (emit "BEGIN brush-fill-preparation v2")
      (emit "CAPS parents=250 calls=60000 objects=10000 members=1000")
      (dolist (name '("SCRIPT" "CFLIST" "CFRAME" "SCAN-ROW" "PATCH-EDGE")) (install name))
      (dolist (name '("MY-FILL" "BRUSH-FILL-SUBPART")) (exclude name))
      (let* ((symbol (find-symbol "PATCHDEX" owner)) (original (symbol-function symbol)))
        (setf (symbol-function symbol)
              (lambda (&rest args)
                (multiple-value-call
                    (lambda (&rest values)
                      (when (and report active (= busy 0))
                        (setf last-patch
                              (snapshot :patch-reader
                                        (lambda ()
                                          (unless (and (= (length args) 1) (= (length values) 1)
                                                       (integerp (car values))) (error "Unsupported patch reader"))
                                          (list (object-id (car args)) (car values))))))
                      (values-list values))
                  (apply original args)))))
      (let* ((symbol (find-symbol "BRUSH-FILL" owner)) (original (symbol-function symbol)))
        (setf (symbol-function symbol)
              (lambda (&rest args)
                (let ((id (incf parents)) (completed nil))
                  (when (or active (> id 250)) (setf overflow t) (error "Preparation parent cap/nesting"))
                  (setf active id last-frame nil last-form nil last-patch nil last-scan nil)
                  (emit "PARENT id=~D args=~S mplan=~D" id args (object-id (global "MPLAN")))
                  (unwind-protect
                      (multiple-value-prog1 (apply original args) (setf completed t) (emit "END-PARENT id=~D" id))
                    (unless completed (incf aborts) (emit "ABORT-PARENT id=~D" id))
                    (setf active nil))))))
      (let* ((symbol (find-symbol "MAIN" owner)) (original (symbol-function symbol)))
        (setf (symbol-function symbol)
              (lambda (&rest args)
                (let ((completed nil))
                  (unwind-protect
                      (multiple-value-prog1 (apply original args) (setf completed t) (finish :normal))
                    (unless completed (finish :aborted)))))))
      (emit "READY") (finish-output report))))
