;;; Complete natural brush boundary census; no extra AARON accessor calls.
(in-package :cl-user)
(unless (boundp 'aaron-brush-stroke-census-loaded)
  (set 'aaron-brush-stroke-census-loaded t)
  (let* ((owner (find-package "COMMON-GRAPHICS-USER"))
         (report (open "C:\\temp\\aaron-brush-stroke-census.txt" :direction :output
                       :if-exists :supersede :if-does-not-exist :create))
         (calls 0) (clears 0) (screens 0) (predicates 0) (x-reads 0) (y-reads 0) (core-reads 0)
         (checks 0) (errors 0) (aborts 0) (overflow nil) (current nil) (in-screen nil)
         (seen-brushes (make-hash-table :test #'eq)))
    (labels
        ((emit (control &rest args)
           (when report
             (handler-case
                 (let ((*print-length* nil) (*print-level* nil) (*print-pretty* nil)
                       (*print-circle* nil) (*print-readably* nil))
                   (apply #'format report control args) (terpri report))
               (condition () (incf errors)))))
         (problem (phase condition)
           (incf errors) (emit "ERROR phase=~S type=~S message=~S" phase
                              (format nil "~S" (type-of condition)) (format nil "~A" condition)))
         (limit (kind amount)
           (setf overflow t) (emit "OVERFLOW kind=~S amount=~D" kind amount) (error "Census observation cap"))
         (global (name)
           (let ((symbol (find-symbol name owner)))
             (unless (and symbol (boundp symbol)) (error "Missing binding ~A" name)) (symbol-value symbol)))
         (bounded-length (value)
           (let ((tail value) (n 0) (seen (make-hash-table :test #'eq)))
             (do () ((not (consp tail)))
               (when (gethash tail seen) (error "Cyclic path")) (setf (gethash tail seen) t)
               (incf n) (when (> n 10000) (limit :path n)) (setf tail (cdr tail)))
             (unless (null tail) (error "Improper path")) n))
         (observe (phase thunk)
           (handler-case
               (let* ((preview (aaron-random-state-preview)) (value (funcall thunk)))
                 (unless (and (eq (car preview) :random-100-1) (equal preview (aaron-random-state-preview)))
                   (error "Observation changed copied random preview")) (incf checks) value)
             (condition (condition) (problem phase condition) nil)))
         (before (args)
           (unless (and (= (length args) 4) (every #'integerp (cdr args))) (error "Unexpected stroke arguments"))
           (let* ((brush (global "BRUSH")) (map (global "FILL-MAP"))
                  (index (position brush (global "ALL-BRUSHES") :test #'eq)))
             (unless (and (arrayp map) (= (array-rank map) 2)
                          (equal (array-element-type map) '(unsigned-byte 4))) (error "Unexpected fill map"))
             (when (and brush (not (gethash brush seen-brushes)))
               (setf (gethash brush seen-brushes) t)
               (let ((core (slot-value brush (find-symbol "CORE" owner))))
                 (bounded-length core)
                 (emit "BRUSH index=~S type=~S core=~S" index (format nil "~S" (type-of brush)) core)))
             (list :path-length (bounded-length (car args)) :value (second args) :cdex (third args) :sdex (fourth args)
                   :brush-index index :brush-type (format nil "~S" (type-of brush)) :map-dimensions (array-dimensions map))))
         (results (values)
           (when (> (length values) 16) (limit :values (length values)))
           (mapcar (lambda (value) (cond ((null value) (list :nil))
                                        ((integerp value) (list :integer value))
                                        (t (list :object (format nil "~S" (type-of value)))))) values))
         (install-reader (name)
           (let* ((symbol (find-symbol name owner)) (original (symbol-function symbol)))
             (emit "INSTALL name=~S type=~S" name (format nil "~S" (type-of original)))
             (setf (symbol-function symbol)
                   (lambda (&rest args)
                     (multiple-value-call
                         (lambda (&rest values)
                           (when report
                             (handler-case
                                 (cond
                                   ((string= name "IN-SUB-FRAME")
                                    (incf predicates)
                                    (when current
                                      (incf (getf current (if in-screen :screen-predicates :predicates)))
                                      (if (car values) (incf (getf current :accepted)) (incf (getf current :rejected)))))
                                   ((string= name "CORE") (incf core-reads) (when current (incf (getf current :core-reads))))
                                   ((string= name "X") (incf x-reads) (when current (incf (getf current :x-reads))))
                                   ((string= name "Y") (incf y-reads) (when current (incf (getf current :y-reads)))))
                               (condition (condition) (problem :reader condition))))
                           (values-list values)) (apply original args))))))
         (install-boundary (name)
           (let* ((symbol (find-symbol name owner)) (original (symbol-function symbol)))
             (emit "INSTALL name=~S type=~S" name (format nil "~S" (type-of original)))
             (setf (symbol-function symbol)
                   (lambda (&rest args)
                     (if (null report) (apply original args)
                       (cond
                         ((string= name "BRUSH-STROKE")
                          (let* ((id (incf calls)) (prior current) (completed nil)
                                 (context (list :predicates 0 :screen-predicates 0 :accepted 0 :rejected 0 :screens 0
                                                :x-reads 0 :y-reads 0 :core-reads 0)))
                            (when (or current (> id 50000)) (limit :calls id)) (setf current context)
                            (emit "CALL id=~D before=~S" id (observe :before (lambda () (before args))))
                            (unwind-protect
                                (multiple-value-call
                                    (lambda (&rest values)
                                      (setf completed t) (emit "RETURN id=~D values=~S counts=~S" id (results values) context)
                                      (values-list values)) (apply original args))
                              (unless completed (incf aborts) (emit "ABORT id=~D" id)) (setf current prior))))
                         ((string= name "SCREEN-AND-STORE")
                          (incf screens) (when current (incf (getf current :screens)))
                          (let ((prior-screen in-screen))
                            (setf in-screen t)
                            (unwind-protect (apply original args) (setf in-screen prior-screen))))
                         (t (incf clears) (apply original args))))))))
         (finish (status)
           (emit "COMPLETE main=~S calls=~D clears=~D screens=~D predicates=~D x-reads=~D y-reads=~D core-reads=~D checks=~D errors=~D aborts=~D overflow=~S active=~S"
                 status calls clears screens predicates x-reads y-reads core-reads checks errors aborts overflow (not (null current)))
           (emit "END brush-stroke-census v1") (finish-output report) (close report) (setf report nil)))
      (emit "BEGIN brush-stroke-census v1") (emit "CAPS calls=50000 path=10000 values=16")
      (dolist (name '("IN-SUB-FRAME" "X" "Y" "CORE")) (install-reader name))
      (dolist (name '("BRUSH-STROKE" "SCREEN-AND-STORE" "CLEAR-FILL-MAP")) (install-boundary name))
      (let* ((symbol (find-symbol "MAIN" owner)) (original (symbol-function symbol)))
        (setf (symbol-function symbol)
              (lambda (&rest args)
                (let ((completed nil))
                  (unwind-protect
                      (multiple-value-prog1 (apply original args) (setf completed t) (finish :normal))
                    (unless completed (finish :aborted)))))))
      (emit "READY") (finish-output report))))
