;;; Complete natural BRUSH-STROKE value-3 and CLEAR-FILL-MAP boundaries.
;;; All other natural BRUSH-STROKE entries are retained in the chronology.
;;; Observation uses copied maps and direct slot reads; no extra AARON calls.
(in-package :cl-user)

(unless (boundp 'aaron-brush-stroke-boundary-capture-loaded)
  (set 'aaron-brush-stroke-boundary-capture-loaded t)
  (let* ((owner (find-package "COMMON-GRAPHICS-USER"))
         (report (open "C:\\temp\\aaron-brush-stroke-boundary.txt"
                       :direction :output :if-exists :supersede :if-does-not-exist :create))
         (object-ids (make-hash-table :test #'eq)) (objects 0)
         (strokes 0) (sampled 0) (clears 0) (events 0)
         (predicates 0) (screens 0) (frame-reads 0)
         (points 0) (cells 0) (runs 0) (checks 0)
         (errors 0) (aborts 0) (overflow nil)
         (current-stroke nil) (current-clear nil)
         (latest-value3 0) (other-strokes-after-value3 0))
    (labels
        ((emit (control &rest args)
           (when report
             (handler-case
                 (let ((*print-length* nil) (*print-level* nil) (*print-pretty* nil)
                       (*print-circle* nil) (*print-readably* nil))
                   (apply #'format report control args)
                   (terpri report))
               (condition () (incf errors)))))
         (problem (phase condition)
           (incf errors)
           (emit "ERROR phase=~S type=~S message=~S"
                 phase (format nil "~S" (type-of condition)) (format nil "~A" condition)))
         (limit (kind amount)
           (setf overflow t)
           (emit "OVERFLOW kind=~S amount=~D" kind amount)
           (error "Brush-stroke boundary observation cap"))
         (next-event ()
           (incf events)
           (when (> events 4000000)
             (setf overflow t)
             (emit "OVERFLOW kind=:EVENTS amount=~D" events))
           events)
         (global-symbol (name)
           (let* ((symbol (find-symbol name owner))
                  (graphics (find-package "COMMON-GRAPHICS"))
                  (fallback (and graphics (find-symbol name graphics))))
             (cond ((and symbol (boundp symbol)) symbol)
                   ((and fallback (boundp fallback)) fallback)
                   (t nil))))
         (global (name)
           (let ((symbol (global-symbol name)))
             (unless symbol (error "Missing binding ~A" name))
             (symbol-value symbol)))
         (slot-symbol (name)
           (or (find-symbol name owner)
               (let ((graphics (find-package "COMMON-GRAPHICS")))
                 (and graphics (find-symbol name graphics)))
               (error "Missing slot symbol ~A" name)))
         (object-id (object)
           (if (null object) 0
             (or (gethash object object-ids)
                 (let ((id (incf objects)))
                   (when (> objects 30000) (limit :objects objects))
                   (setf (gethash object object-ids) id)
                   (emit "OBJECT id=~D type=~S" id (format nil "~S" (type-of object)))
                   id))))
         (descriptor (value)
           (cond ((null value) (list :nil))
                 ((integerp value) (list :integer value))
                 ((characterp value) (list :character (char-code value)))
                 ((stringp value)
                  (list :string (subseq value 0 (min 256 (length value))) (length value)))
                 ((symbolp value)
                  (list :symbol (if (symbol-package value)
                                    (package-name (symbol-package value)) "UNINTERNED")
                        (symbol-name value)))
                 ((numberp value) (list :number (format nil "~S" value)))
                 (t (list :object (object-id value) (format nil "~S" (type-of value))))))
         (descriptors (values)
           (when (> (length values) 16) (limit :values (length values)))
           (mapcar #'descriptor values))
         (proper-length (value kind cap)
           (let ((tail value) (count 0) (seen (make-hash-table :test #'eq)))
             (do () ((not (consp tail)))
               (when (gethash tail seen) (error "Cyclic ~A list" kind))
               (setf (gethash tail seen) t)
               (incf count)
               (when (> count cap) (limit kind count))
               (setf tail (cdr tail)))
             (unless (null tail) (error "Improper ~A list" kind))
             count))
         (point-record (point)
           (if (null point)
               (list :id 0 :type "NULL" :x nil :y nil)
             (let ((x (slot-value point (slot-symbol "X")))
                   (y (slot-value point (slot-symbol "Y"))))
               (unless (and (integerp x) (integerp y)) (error "Noninteger point coordinate"))
               (list :id (object-id point) :type (format nil "~S" (type-of point)) :x x :y y))))
         (path-record (path)
           (cond
             ((null path) (list :id 0 :type "NULL" :length 0 :points nil))
             ((consp path)
              (let ((count (proper-length path :path 20000)) (points-list nil))
                (when (> (+ points count) 1000000) (limit :points (+ points count)))
                (incf points count)
                (dolist (point path) (push (point-record point) points-list))
                (list :id (object-id path) :type (format nil "~S" (type-of path))
                      :length count :points (nreverse points-list))))
             (t (error "BRUSH-STROKE path is not NIL or a proper list"))))
         (offset-record (offsets name)
           (let ((count (proper-length offsets name 10000)) (result nil))
             (dolist (offset offsets)
               (unless (and (consp offset) (consp (cdr offset)) (null (cddr offset))
                            (integerp (first offset)) (integerp (second offset)))
                 (error "Malformed ~A offset" name))
               (push (list (first offset) (second offset)) result))
             (list :length count :offsets (nreverse result))))
         (brush-index (brush)
           (let ((brushes (global "ALL-BRUSHES")) (tail nil) (index 0)
                 (found nil) (answer nil) (seen (make-hash-table :test #'eq)))
             (setf tail brushes)
             (do () ((not (consp tail)))
               (when (gethash tail seen) (error "Cyclic ALL-BRUSHES list"))
               (setf (gethash tail seen) t)
               (when (> index 1000) (limit :brush-list index))
               (when (and (not found) (eq (car tail) brush)) (setf found t answer index))
               (incf index) (setf tail (cdr tail)))
             (unless (null tail) (error "Improper ALL-BRUSHES list"))
             answer))
         (brush-record ()
           (let ((brush (global "BRUSH")))
             (if (null brush)
                 (list :id 0 :type "NULL" :index nil :perim nil :core nil)
               (list :id (object-id brush) :type (format nil "~S" (type-of brush))
                     :index (brush-index brush)
                     :perim (offset-record (slot-value brush (slot-symbol "PERIM")) :perim)
                     :core (offset-record (slot-value brush (slot-symbol "CORE")) :core)))))
         (binding-record (name)
           (let ((symbol (global-symbol name)))
             (if symbol (list :bound (descriptor (symbol-value symbol))) (list :unbound))))
         (frame-bounds (frame)
           (let ((values nil))
             (dolist (name '("LX" "RX" "LY" "TY"))
               (let ((value (slot-value frame (slot-symbol name))))
                 (unless (integerp value) (error "Noninteger ~A frame bound" name))
                 (push (list name value) values)))
             (nreverse values)))
         (dynamic-record ()
           (let* ((frame (global "SUB-FRAME")) (brush (global "BRUSH"))
                  (width (if brush (slot-value brush (slot-symbol "WIDTH")) nil)))
             (unless frame (error "SUB-FRAME is NIL at value-3 boundary"))
             (unless (and brush (integerp width)) (error "Missing integer BRUSH WIDTH slot"))
             (list :sub-frame (list :id (object-id frame) :type (format nil "~S" (type-of frame))
                                    :bounds (frame-bounds frame))
                   :width width :boundary-value (binding-record "BOUNDARY-VALUE"))))
         (flat-map (map)
           (unless (and (arrayp map) (= (array-rank map) 2)
                        (equal (array-element-type map) '(unsigned-byte 4)))
             (error "Expected rank-two unsigned-byte-4 FILL-MAP"))
           (let* ((width (array-dimension map 0)) (height (array-dimension map 1))
                  (count (* width height)))
             (unless (and (> width 0) (> height 0) (<= count 153600))
               (limit :map-cells count))
             (when (> (+ cells count) 100000000) (limit :cells (+ cells count)))
             (incf cells count)
             (list (copy-seq (make-array (array-total-size map)
                                         :element-type '(unsigned-byte 4) :displaced-to map))
                   width height map)))
         (map-record (flat width height map)
           (let ((rows nil) (local-runs 0))
             (dotimes (y height)
               (let ((row nil) (last nil) (count 0))
                 (dotimes (x width)
                   (let ((next (aref flat (+ (* x height) y))))
                     (if (and (> count 0) (= next last))
                         (incf count)
                       (progn
                         (when (> count 0)
                           (push (list last count) row) (incf local-runs))
                         (setf last next count 1)))))
                 (when (> count 0) (push (list last count) row) (incf local-runs))
                 (push (list y (nreverse row)) rows)))
             (incf runs local-runs)
             (when (> runs 6000000) (limit :runs runs))
             (list :id (object-id map) :type (format nil "~S" (type-of map))
                   :element-type (array-element-type map) :width width :height height
                   :cells (* width height) :covered (* width height) :complete t
                   :runs local-runs :rows (nreverse rows))))
         (snapshot (phase thunk)
           (handler-case
               (let* ((preview (aaron-random-state-preview)) (result (funcall thunk)))
                 (unless (and (eq (car preview) :random-100-1)
                              (equal preview (aaron-random-state-preview)))
                   (error "Snapshot changed copied random-state preview"))
                 (incf checks)
                 result)
             (condition (condition) (problem phase condition) (list :capture-error phase))))
         (safe-observe (phase thunk)
           (if overflow (list :capture-skipped phase) (snapshot phase thunk)))
         (safe-log (phase thunk)
           (handler-case (funcall thunk)
             (condition (condition) (problem phase condition) nil)))
         (stroke-input (context)
           (let* ((args (getf context :args)) (path (first args))
                  (brush (global "BRUSH")) (map (global "FILL-MAP"))
                  (copy (flat-map map)))
             (list :path (path-record path) :brush (brush-record)
                   :brush-boundary-value (descriptor (second args))
                   :configuration (dynamic-record)
                   :map (map-record (first copy) (second copy) (third copy) (fourth copy))
                   :map-object-id (object-id map) :brush-object-id (object-id brush))))
         (stroke-output (context values)
           (let* ((args (getf context :args)) (path (first args))
                  (brush (global "BRUSH")) (map (global "FILL-MAP"))
                  (copy (flat-map map)))
             (list :values (descriptors values)
                   :return-path-eq (and values (eq (first values) path))
                   :path (path-record path) :brush (brush-record)
                   :brush-boundary-value (descriptor (second args))
                   :configuration (dynamic-record)
                   :map (map-record (first copy) (second copy) (third copy) (fourth copy))
                   :map-object-id (object-id map) :brush-object-id (object-id brush))))
         (clear-map-record ()
           (let* ((map (global "FILL-MAP")) (copy (flat-map map)))
             (map-record (first copy) (second copy) (third copy) (fourth copy))))
         (capture-frame (args values event)
           (let* ((frame (first values))
                  (bounds (when frame
                            (let ((values nil))
                              (dolist (name '("LX" "RX" "LY" "TY"))
                                (let ((value (slot-value frame (slot-symbol name))))
                                  (unless (integerp value) (error "Noninteger CFRAME bound"))
                                  (push (list name value) values)))
                              (nreverse values))))
                  (record (list :event event :args (descriptors args)
                                :values (descriptors values)
                                :argument-id (if args (object-id (first args)) 0)
                                :frame-id (object-id frame)
                                :frame-type (if frame (format nil "~S" (type-of frame)) "NULL")
                                :bounds bounds)))
             (push record (getf current-clear :frames))
             (emit "CFRAME event=~D clear=~D data=~S"
                   event (getf current-clear :id) record)))
         (record-main-finish (status)
           (emit "COMPLETE main=~S strokes=~D sampled=~D clears=~D events=~D predicates=~D screens=~D frame-reads=~D points=~D cells=~D runs=~D objects=~D checks=~D errors=~D aborts=~D overflow=~S stroke-active=~S clear-active=~S"
                 status strokes sampled clears events predicates screens frame-reads points cells runs objects checks
                 errors aborts overflow (not (null current-stroke)) (not (null current-clear)))
           (emit "END brush-stroke-boundary v1")
           (when report (finish-output report) (close report) (setf report nil)))
         (install (name)
           (let* ((symbol (find-symbol name owner)) (original (symbol-function symbol)))
             (emit "INSTALL name=~S type=~S" name (format nil "~S" (type-of original)))
             (cond
               ((string= name "IN-SUB-FRAME")
                (setf (symbol-function symbol)
                      (lambda (&rest args)
                        (let ((event (if (and report (not overflow)) (next-event) 0)) (completed nil))
                          (when report
                            (incf predicates)
                            (when (> predicates 2000000)
                              (setf overflow t)
                              (emit "OVERFLOW kind=:PREDICATES amount=~D" predicates)))
                          (unwind-protect
                              (multiple-value-call
                                  (lambda (&rest values)
                                    (setf completed t)
                                    (when (and report current-stroke (getf current-stroke :sampled) (not overflow))
                                      (incf (getf current-stroke :predicates))
                                      (safe-log :predicate
                                        (lambda ()
                                          (emit "IN-SUB-FRAME event=~D stroke=~D args=~S values=~S"
                                                event (getf current-stroke :id) (descriptors args) (descriptors values)))))
                                    (values-list values))
                                (apply original args))
                            (unless completed (incf aborts) (emit "ABORT kind=:IN-SUB-FRAME event=~D" event)))))))
               ((string= name "SCREEN-AND-STORE")
                (setf (symbol-function symbol)
                      (lambda (&rest args)
                        (let* ((event (if (and report (not overflow)) (next-event) 0))
                               (active (and report current-stroke (getf current-stroke :sampled) (not overflow)))
                               (completed nil))
                          (when report (incf screens))
                          (when active (incf (getf current-stroke :screens)))
                          (when active
                            (safe-observe :screen-entry
                              (lambda ()
                                (emit "SCREEN-BEGIN event=~D stroke=~D args=~S path-id=~D path-eq=~S cdex=~S sdex=~S"
                                      event (getf current-stroke :id) (descriptors args)
                                      (if args (object-id (first args)) 0)
                                      (and args (eq (first args) (getf current-stroke :path)))
                                      (if (> (length args) 1) (descriptor (second args)) (list :missing))
                                      (if (> (length args) 2) (descriptor (third args)) (list :missing))))))
                          (unwind-protect
                              (multiple-value-call
                                  (lambda (&rest values)
                                    (setf completed t)
                                    (when active
                                      (safe-observe :screen-return
                                        (lambda ()
                                          (emit "SCREEN-RETURN event=~D stroke=~D values=~S return-path-eq=~S"
                                                event (getf current-stroke :id) (descriptors values)
                                                (and values (eq (first values) (getf current-stroke :path)))))))
                                    (values-list values))
                                (apply original args))
                            (unless completed (incf aborts) (emit "ABORT kind=:SCREEN-AND-STORE event=~D" event)))))))
               ((string= name "CFRAME")
                (setf (symbol-function symbol)
                      (lambda (&rest args)
                        (if (or (null report) overflow (null current-clear))
                            (apply original args)
                          (let ((event (next-event)) (completed nil))
                            (incf frame-reads)
                            (unwind-protect
                                (multiple-value-call
                                    (lambda (&rest values)
                                      (setf completed t)
                                      (safe-observe :frame
                                        (lambda () (capture-frame args values event)))
                                      (values-list values))
                                  (apply original args))
                              (unless completed (incf aborts) (emit "ABORT kind=:CFRAME event=~D" event))))))))
               ((string= name "BRUSH-STROKE")
                (setf (symbol-function symbol)
                      (lambda (&rest args)
                        (let* ((id (incf strokes))
                               (value (if (> (length args) 1) (second args) :missing))
                               (sampled-call (eql value 3))
                               (event (if (and report (not overflow)) (next-event) 0)))
                          (when sampled-call
                            (setf latest-value3 id other-strokes-after-value3 0)
                            (incf sampled))
                          (when (and (> latest-value3 0) (not sampled-call))
                            (incf other-strokes-after-value3))
                          (if (or (null report) overflow (> id 5000) (and sampled-call (> sampled 250)))
                              (progn
                                (when (and report (not overflow)
                                           (or (> id 5000) (and sampled-call (> sampled 250))))
                                  (setf overflow t)
                                  (emit "OVERFLOW kind=~S amount=~D"
                                        (if sampled-call :sampled :strokes) (if sampled-call sampled id)))
                                (apply original args))
                            (let* ((prior current-stroke) (completed nil)
                                   (context (list :id id :event event :args args :path (first args)
                                                  :value value :sampled sampled-call :predicates 0 :screens 0)))
                              (setf current-stroke context)
                              (safe-observe :stroke-entry
                                (lambda ()
                                  (emit "STROKE-BEGIN id=~D event=~D argc=~D args=~S value=~S path-id=~D path-length=~D sampled=~S"
                                        id event (length args) (descriptors args) (descriptor value)
                                        (if args (object-id (first args)) 0)
                                        (if (consp (first args)) (proper-length (first args) :path 20000)
                                          (if (null (first args)) 0 -1)) sampled-call)))
                              (when sampled-call
                                (emit "STROKE-INPUT id=~D event=~D data=~S"
                                      id event (safe-observe :stroke-input (lambda () (stroke-input context)))))
                              (unwind-protect
                                  (multiple-value-call
                                      (lambda (&rest values)
                                        (setf completed t)
                                        (if sampled-call
                                            (emit "STROKE-RETURN id=~D event=~D predicates=~D screens=~D data=~S"
                                                  id event (getf context :predicates) (getf context :screens)
                                                  (safe-observe :stroke-output (lambda () (stroke-output context values))))
                                          (safe-observe :stroke-return
                                            (lambda ()
                                              (emit "STROKE-RETURN id=~D event=~D values=~S return-path-eq=~S"
                                                    id event (descriptors values)
                                                    (and values (eq (first values) (first args)))))))
                                        (values-list values))
                                    (apply original args))
                                (unless completed (incf aborts) (emit "ABORT kind=:BRUSH-STROKE id=~D" id))
                                (setf current-stroke prior))))))))
               ((string= name "CLEAR-FILL-MAP")
                (setf (symbol-function symbol)
                      (lambda (&rest args)
                        (let ((id (incf clears)))
                          (if (or (null report) overflow (> id 250))
                              (progn
                                (when (and report (not overflow) (> id 250))
                                  (setf overflow t) (emit "OVERFLOW kind=:CLEARS amount=~D" id))
                                (apply original args))
                            (let* ((event (next-event)) (prior current-clear) (completed nil)
                                   (context (list :id id :event event :args args :frames nil)))
                              (setf current-clear context)
                              (safe-observe :clear-entry
                                (lambda ()
                                  (emit "CLEAR-BEGIN id=~D event=~D args=~S latest-value3=~D other-strokes-after-value3=~D map=~S"
                                        id event (descriptors args) latest-value3 other-strokes-after-value3
                                        (clear-map-record))))
                              (unwind-protect
                                  (multiple-value-call
                                      (lambda (&rest values)
                                        (setf completed t)
                                        (safe-observe :clear-return
                                          (lambda ()
                                            (emit "CLEAR-RETURN id=~D event=~D values=~S latest-value3=~D other-strokes-after-value3=~D frames=~S map=~S"
                                                  id event (descriptors values) latest-value3 other-strokes-after-value3
                                                  (nreverse (getf context :frames)) (clear-map-record))))
                                        (values-list values))
                                    (apply original args))
                                (unless completed (incf aborts) (emit "ABORT kind=:CLEAR-FILL-MAP id=~D" id))
                                (setf current-clear prior))))))))
             ))))
      (emit "BEGIN brush-stroke-boundary v1")
      (emit "CAPS strokes=5000 sampled=250 clears=250 events=4000000 points=1000000 map-cells=153600 total-cells=100000000 runs=6000000 predicates=2000000 objects=30000 values=16 path=20000 offsets=10000")
      (dolist (name '("IN-SUB-FRAME" "SCREEN-AND-STORE" "CFRAME" "BRUSH-STROKE" "CLEAR-FILL-MAP"))
        (install name))
      (let* ((symbol (find-symbol "MAIN" owner)) (original (symbol-function symbol)))
        (emit "INSTALL name=~S type=~S" "MAIN" (format nil "~S" (type-of original)))
        (setf (symbol-function symbol)
              (lambda (&rest args)
                (let ((completed nil))
                  (unwind-protect
                      (multiple-value-prog1 (apply original args)
                        (setf completed t) (record-main-finish :normal))
                    (unless completed (record-main-finish :aborted)))))))
      (emit "READY")
      (finish-output report))))
