;;; Bounded natural buffer/brush attribution tape.
;;; Observe existing calls and direct slots only; no target is invoked by the probe.
(in-package :cl-user)

(unless (boundp 'aaron-brush-buffer-capture-loaded)
  (set 'aaron-brush-buffer-capture-loaded t)
  (let* ((owner (find-package "COMMON-GRAPHICS-USER"))
         (report (open "C:\\temp\\aaron-brush-buffer.txt"
                       :direction :output :if-exists :supersede
                       :if-does-not-exist :create))
         (targets '("BRUSH-FILL-SUBPART" "BUFFER-HEAD" "BUFFER-ANYTHING"
                    "BUFFER-FEATURE" "BUFFER-HOLE" "EDGE" "ZERO-EDGE"
                    "CFRAME" "IN-SUB-FRAME" "FOOB" "BRUSH-STROKE"
                    "CLEAR-FILL-MAP"))
         (global-counts (make-hash-table :test #'equal))
         (sampled-counts (make-hash-table :test #'equal))
         (object-ids (make-hash-table :test #'eq))
         (objects 0) (calls 0) (events 0) (points 0) (cells 0) (runs 0)
         (checks 0) (errors 0) (aborts 0) (overflow nil) (predicates 0)
         (parents 0) (buffers 0) (children 0) (strokes 0) (markers 0)
         (clears 0)
         (current-parent 0) (current-buffer 0) (current-child 0)
         (current-stroke 0) (current-clear 0)
         (attribution-active nil) (attribution-marker 0)
         (attribution-parent 0) (attribution-buffer 0)
         (attribution-child 0) (attribution-stroke 0))
    (labels
        ((emit (control &rest args)
           (when report
             (handler-case
                 (let ((*print-length* nil) (*print-level* nil)
                       (*print-pretty* nil) (*print-circle* nil)
                       (*print-readably* nil))
                   (apply #'format report control args)
                   (terpri report))
               (condition () (incf errors)))))
         (problem (phase condition)
           (incf errors)
           (handler-case
               (emit "ERROR phase=~S type=~S text=~S"
                     phase (format nil "~S" (type-of condition))
                     (format nil "~A" condition))
             (condition () nil)))
         (mark-overflow (kind amount)
           (unless overflow
             (setf overflow t)
             (emit "OVERFLOW kind=~S amount=~D" kind amount)))
         (next-event ()
           (incf events)
           (when (> events 4000000) (mark-overflow :events events))
           events)
         (next-call ()
           (incf calls)
           (when (> calls 10000000) (mark-overflow :calls calls))
           calls)
         (bump-count (table name)
           (setf (gethash name table) (1+ (gethash name table 0))))
         (global-symbol (name)
           (let* ((symbol (and owner (find-symbol name owner)))
                  (graphics (find-package "COMMON-GRAPHICS"))
                  (fallback (and graphics (find-symbol name graphics))))
             (cond ((and symbol (boundp symbol)) symbol)
                   ((and fallback (boundp fallback)) fallback)
                   (t nil))))
         (global-value (name)
           (let ((symbol (global-symbol name)))
             (if symbol (values (symbol-value symbol) t) (values nil nil))))
         (slot-symbol (name)
           (or (and owner (find-symbol name owner))
               (let ((graphics (find-package "COMMON-GRAPHICS")))
                 (and graphics (find-symbol name graphics)))
               (error "Missing slot symbol ~A" name)))
         (object-id (object)
           (if (null object) 0
             (or (gethash object object-ids)
                 (if (>= objects 50000)
                     (progn (mark-overflow :objects (1+ objects)) 0)
                   (let ((id (incf objects)))
                     (setf (gethash object object-ids) id)
                     (emit "OBJECT id=~D type=~S"
                           id (format nil "~S" (type-of object)))
                     id)))))
         (descriptor (value)
           (cond ((null value) (list :nil))
                 ((integerp value) (list :integer value))
                 ((numberp value)
                  (list :number (format nil "~S" value)
                        (format nil "~S" (type-of value))))
                 ((characterp value) (list :character (char-code value)))
                 ((stringp value)
                  (list :string (subseq value 0 (min 256 (length value)))
                        (length value)))
                 ((symbolp value)
                  (list :symbol (if (symbol-package value)
                                    (package-name (symbol-package value))
                                    "UNINTERNED")
                        (symbol-name value)))
                 (t (list :object (object-id value)
                          (format nil "~S" (type-of value))))))
         (descriptors (values)
           (when (> (length values) 16)
             (mark-overflow :values (length values))
             (error "Observer value-count cap exceeded"))
           (mapcar #'descriptor values))
         (proper-length (value kind)
           (let ((tail value) (count 0) (seen (make-hash-table :test #'eq)))
             (do () ((not (consp tail)))
               (when (gethash tail seen) (error "Cyclic ~A list" kind))
               (setf (gethash tail seen) t)
               (incf count)
               (when (> count 20000)
                 (mark-overflow kind count)
                 (error "Observer proper-list cap exceeded for ~A" kind))
               (setf tail (cdr tail)))
             (unless (null tail) (error "Improper ~A list" kind))
             count))
         (coordinate-record (point)
           (if (null point)
               (list :id 0 :type "NULL" :x (list :nil) :y (list :nil))
             (let ((x (slot-value point (slot-symbol "X")))
                   (y (slot-value point (slot-symbol "Y"))))
               (unless (and (numberp x) (numberp y))
                 (error "Point has nonnumeric coordinates"))
               (incf points)
               (when (> points 1000000)
                 (mark-overflow :points points)
                 (error "Observer point cap exceeded"))
               (list :id (object-id point) :type (format nil "~S" (type-of point))
                     :x (descriptor x) :y (descriptor y)))))
         (point-list-record (value kind)
           (cond ((null value) (list :kind kind :id 0 :type "NULL"
                                    :length 0 :points nil))
                 ((consp value)
                  (let ((count (proper-length value kind)) (items nil))
                    (dolist (point value)
                      (push (coordinate-record point) items))
                    (list :kind kind :id (object-id value)
                          :type (format nil "~S" (type-of value))
                          :length count :points (nreverse items))))
                 (t (list :kind kind :non-list (descriptor value)))))
         (path-summary (path &optional full)
           (cond ((null path)
                  (list :id 0 :type "NULL" :length 0 :points nil))
                 ((consp path)
                  (let ((count (proper-length path :path)))
                    (list :id (object-id path) :type (format nil "~S" (type-of path))
                          :length count
                          :points (if full
                                      (getf (point-list-record path :path) :points)
                                      :omitted))))
                 (t (error "BRUSH-STROKE path is not NIL or a proper list"))))
         (offset-record (offsets kind)
           (let ((count (proper-length offsets kind)) (items nil))
             (when (> count 10000)
               (mark-overflow kind count)
               (error "Observer offset cap exceeded for ~A" kind))
             (dolist (offset offsets)
               (unless (and (consp offset) (consp (cdr offset))
                            (null (cddr offset))
                            (integerp (first offset)) (integerp (second offset)))
                 (error "Malformed ~A offset pair" kind))
               (push (list (first offset) (second offset)) items))
             (nreverse items)))
         (brush-record ()
           (multiple-value-bind (brush bound) (global-value "BRUSH")
             (if (not bound) (list :unbound)
               (if (null brush) (list :nil)
                 (list :id (object-id brush) :type (format nil "~S" (type-of brush))
                       :width (descriptor (slot-value brush (slot-symbol "WIDTH")))
                       :core (offset-record (slot-value brush (slot-symbol "CORE"))
                                             :core)
                       :perim (offset-record (slot-value brush (slot-symbol "PERIM"))
                                             :perim))))))
         (frame-record (frame)
           (if (null frame) (list :nil)
             (let ((bounds nil))
               (dolist (name '("LX" "RX" "LY" "TY"))
                 (push (list name
                             (descriptor (slot-value frame (slot-symbol name))))
                       bounds))
               (list :id (object-id frame) :type (format nil "~S" (type-of frame))
                     :bounds (nreverse bounds)))))
         (map-meta (map)
           (unless (arrayp map) (error "FILL-MAP is not an array"))
           (let* ((rank (array-rank map))
                  (element-type (array-element-type map)))
             (list :id (object-id map) :type (format nil "~S" (type-of map))
                   :rank rank :element-type element-type
                   :width (if (= rank 2) (array-dimension map 0) nil)
                   :height (if (= rank 2) (array-dimension map 1) nil))))
         (flat-map (map)
           (unless (and (arrayp map) (= (array-rank map) 2)
                        (equal (array-element-type map) '(unsigned-byte 4)))
             (error "Expected rank-two unsigned-byte-4 FILL-MAP"))
           (let* ((width (array-dimension map 0))
                  (height (array-dimension map 1))
                  (count (* width height)))
             (unless (and (> width 0) (> height 0) (<= count 153600))
               (mark-overflow :cells-per-snapshot count)
               (error "Observer map snapshot cap exceeded"))
             (when (> (+ cells count) 150000000)
               (mark-overflow :total-cells (+ cells count))
               (error "Observer total map-cell cap exceeded"))
             (incf cells count)
             (list (copy-seq (make-array (array-total-size map)
                                         :element-type '(unsigned-byte 4)
                                         :displaced-to map))
                   width height map)))
         (map-record (flat width height map)
           (let ((rows nil) (local-runs 0))
             (dotimes (y height)
               (let ((row nil) (last nil) (length 0))
                 (dotimes (x width)
                   (let ((next (aref flat (+ (* x height) y))))
                     (if (and (> length 0) (= next last))
                         (incf length)
                       (progn
                         (when (> length 0)
                           (push (list last length) row)
                           (incf local-runs)
                           (when (> (+ runs local-runs) 8000000)
                             (mark-overflow :runs (+ runs local-runs))
                             (error "Observer RLE run cap exceeded")))
                         (setf last next length 1)))))
                 (when (> length 0)
                   (push (list last length) row)
                   (incf local-runs)
                   (when (> (+ runs local-runs) 8000000)
                     (mark-overflow :runs (+ runs local-runs))
                     (error "Observer RLE run cap exceeded")))
                 (push (list y (nreverse row)) rows)))
             (incf runs local-runs)
             (when (> runs 8000000)
               (mark-overflow :runs runs)
               (error "Observer RLE run cap exceeded"))
             (list :id (object-id map) :type (format nil "~S" (type-of map))
                   :element-type (array-element-type map) :width width :height height
                   :cells (* width height) :covered (* width height) :complete t
                   :runs local-runs :rows (nreverse rows))))
         (fill-map-record (&optional (given-map nil given-map-p))
           (multiple-value-bind (map bound)
               (if given-map-p (values given-map t) (global-value "FILL-MAP"))
             (unless bound (error "FILL-MAP is unbound"))
             (let ((copy (flat-map map)))
               (map-record (first copy) (second copy) (third copy) (fourth copy)))))
         (feature-state ()
           (multiple-value-bind (frame frame-bound) (global-value "SUB-FRAME")
             (multiple-value-bind (boundary boundary-bound)
                 (global-value "BOUNDARY-VALUE")
               (multiple-value-bind (map map-bound) (global-value "FILL-MAP")
                 (list :brush (brush-record)
                       :sub-frame (if frame-bound (frame-record frame) (list :unbound))
                       :boundary-value (if boundary-bound (descriptor boundary)
                                           (list :unbound))
                       :fill-map (if map-bound (map-meta map) (list :unbound))
                       :map-before (if map-bound (fill-map-record map)
                                       (list :unbound)))))))
         (feature-state-after ()
           (multiple-value-bind (frame frame-bound) (global-value "SUB-FRAME")
             (multiple-value-bind (map map-bound) (global-value "FILL-MAP")
               (multiple-value-bind (boundary boundary-bound)
                   (global-value "BOUNDARY-VALUE")
                 (list :brush-id
                       (multiple-value-bind (brush bound) (global-value "BRUSH")
                         (if (and bound brush) (object-id brush) 0))
                       :sub-frame-id (if (and frame-bound frame) (object-id frame) 0)
                       :fill-map (if map-bound (map-meta map) (list :unbound))
                       :map-after (if map-bound (fill-map-record map)
                                      (list :unbound))
                       :boundary-value (if boundary-bound (descriptor boundary)
                                           (list :unbound)))))))
         (safe-capture (phase thunk)
           (if overflow (list :capture-skipped phase)
             (handler-case
                 (let* ((preview (aaron-random-state-preview))
                        (result (funcall thunk)))
                   (unless (and (eq (car preview) :random-100-1)
                                (equal preview (aaron-random-state-preview)))
                     (error "Snapshot changed copied random-state preview"))
                   (incf checks)
                   result)
               (condition (condition)
                 (problem phase condition)
                  (list :capture-error phase)))))
         (safe-log (phase thunk)
           (handler-case (funcall thunk)
             (condition (condition)
               (handler-case (problem phase condition)
                 (condition () (incf errors)))
               nil)))
         (target-scope (name)
           (cond ((string= name "BRUSH-FILL-SUBPART") :parent)
                 ((or (string= name "BUFFER-HEAD")
                      (string= name "BUFFER-ANYTHING")) :buffer)
                 ((or (string= name "BUFFER-FEATURE")
                      (string= name "BUFFER-HOLE")) :child)
                 ((string= name "BRUSH-STROKE") :stroke)
                 ((string= name "CLEAR-FILL-MAP") :clear)
                 (t :helper)))
         (sample-helper-p (name)
           (cond ((or (string= name "EDGE") (string= name "ZERO-EDGE"))
                  (> current-child 0))
                 ((string= name "CFRAME")
                  (or (> current-parent 0) (> current-clear 0)))
                 ((or (string= name "IN-SUB-FRAME") (string= name "FOOB"))
                  (> current-child 0))
                 (t t)))
         (full-map-target-p (name)
           (or (string= name "BUFFER-HEAD")
               (string= name "BUFFER-ANYTHING")
               (string= name "CLEAR-FILL-MAP")))
         (detail-before (name args)
           (cond ((full-map-target-p name)
                  (safe-capture :map-before #'fill-map-record))
                 ((or (string= name "BUFFER-FEATURE")
                      (string= name "BUFFER-HOLE"))
                  (safe-capture :feature-state-before #'feature-state))
                 ((string= name "BRUSH-STROKE")
                  (let* ((path (first args)) (value (second args))
                         (marker-p (and (integerp value) (= value 3))))
                    (when marker-p
                      (incf markers)
                      (when (> markers 250) (mark-overflow :markers markers)))
                    (list :path (safe-capture :stroke-path
                                              (lambda ()
                                                (path-summary path marker-p)))
                          :value (descriptor value)
                          :marker-p marker-p)))
                 (t nil)))
         (detail-after (name args values)
           (cond ((or (string= name "BUFFER-HEAD")
                      (string= name "BUFFER-ANYTHING"))
                  (safe-capture :map-after #'fill-map-record))
                 ((or (string= name "BUFFER-FEATURE")
                      (string= name "BUFFER-HOLE"))
                  (safe-capture :feature-state-after #'feature-state-after))
                 ((string= name "CLEAR-FILL-MAP") nil)
                 ((string= name "BRUSH-STROKE")
                  (let* ((path (first args)) (value (second args))
                         (marker-p (and (integerp value) (= value 3))))
                    (list :return-path-eq (and values (eq (first values) path))
                          :map-after (if marker-p
                                         (safe-capture :marker-map-after
                                                       #'fill-map-record)
                                       :not-sampled))))
                 ((or (string= name "EDGE") (string= name "ZERO-EDGE"))
                  (list :point-list
                        (safe-capture :helper-points
                                      (lambda ()
                                        (if values
                                            (point-list-record (first values) name)
                                          (list :no-values))))))
                 ((string= name "CFRAME")
                  (list :frame
                        (safe-capture :cframe-bounds
                                      (lambda ()
                                        (if values
                                            (frame-record (first values))
                                          (list :no-values))))))
                 (t nil)))
         (emit-call-begin (name id parent subpart buffer child stroke clear args detail)
           (let ((event (next-event)))
             (unless overflow
               (emit "CALL-BEGIN event=~D target=~S id=~D parent=~D subpart=~D buffer=~D child=~D stroke=~D clear=~D args=~S detail=~S"
                     event name id parent subpart buffer child stroke clear
                     (descriptors args) detail))))
         (emit-call-return (name id parent subpart buffer child stroke clear values detail)
           (let ((event (next-event)))
             (unless overflow
               (emit "CALL-RETURN event=~D target=~S id=~D parent=~D subpart=~D buffer=~D child=~D stroke=~D clear=~D values=~S detail=~S"
                     event name id parent subpart buffer child stroke clear
                     (descriptors values) detail))))
         (emit-call-abort (name id parent subpart buffer child stroke clear)
           (incf aborts)
           (let ((event (next-event)))
             (emit "CALL-ABORT event=~D target=~S id=~D parent=~D subpart=~D buffer=~D child=~D stroke=~D clear=~D"
                   event name id parent subpart buffer child stroke clear)))
         (emit-interval-begin (marker parent buffer child stroke)
           (let ((event (next-event)))
             (unless overflow
               (emit "INTERVAL-BEGIN event=~D marker=~D parent=~D buffer=~D child=~D stroke=~D"
                     event marker parent buffer child stroke))))
         (close-interval (reason clear-id)
           (when attribution-active
             (let ((event (next-event)))
               (unless overflow
                 (emit "INTERVAL-END event=~D marker=~D clear=~D reason=~S parent=~D buffer=~D child=~D stroke=~D"
                       event attribution-marker clear-id reason attribution-parent
                       attribution-buffer attribution-child attribution-stroke)))
             (setf attribution-active nil attribution-marker 0
                   attribution-parent 0 attribution-buffer 0
                   attribution-child 0 attribution-stroke 0)))
         (call-wrapper (name original args)
           (bump-count global-counts name)
           (when (or (string= name "IN-SUB-FRAME") (string= name "FOOB"))
             (incf predicates)
             (when (> predicates 2000000)
               (mark-overflow :predicates predicates)))
           (let* ((scope (target-scope name))
                  (sample (or (not (eq scope :helper)) (sample-helper-p name)))
                  (counter (cond ((eq scope :parent) (incf parents))
                                 ((eq scope :buffer) (incf buffers))
                                 ((eq scope :child) (incf children))
                                 ((eq scope :stroke) (incf strokes))
                                 ((eq scope :clear) (incf clears))))
                  (limit (cond ((eq scope :parent) 250)
                               ((eq scope :buffer) 500)
                               ((eq scope :child) 5000)
                               ((eq scope :stroke) 5000)
                               ((eq scope :clear) 250)))
                  (id (if sample (next-call) 0))
                  (prior-parent current-parent) (prior-buffer current-buffer)
                  (prior-child current-child) (prior-stroke current-stroke)
                  (prior-clear current-clear)
                  (subpart (if (eq scope :parent) id current-parent))
                  (buffer (if (eq scope :buffer) id current-buffer))
                  (child (if (eq scope :child) id current-child))
                  (stroke (if (eq scope :stroke) id current-stroke))
                  (clear (if (eq scope :clear) id current-clear))
                  (marker-p (and (string= name "BRUSH-STROKE")
                                 (integerp (second args)) (= (second args) 3)))
                  (cap-ok (and sample (not overflow)
                               (or (null limit) (<= counter limit)))))
             (when (and limit counter (> counter limit))
               (mark-overflow scope counter))
             (when (and cap-ok marker-p attribution-active)
               (close-interval :next-value3-marker 0))
             (when (and cap-ok (string= name "CLEAR-FILL-MAP")
                        attribution-active)
               (close-interval :clear-entry id))
             (if (not cap-ok)
                 (apply original args)
               (progn
                 (setf current-parent subpart current-buffer buffer
                       current-child child current-stroke stroke
                       current-clear clear)
                 (bump-count sampled-counts name)
                 (safe-log :call-begin
                   (lambda ()
                     (emit-call-begin
                      name id prior-parent subpart buffer child stroke clear args
                      (detail-before name args))))
                 (let ((completed nil))
                   (unwind-protect
                       (multiple-value-call
                           (lambda (&rest values)
                             (setf completed t)
                             (safe-log :call-return
                               (lambda ()
                                 (emit-call-return
                                  name id prior-parent subpart buffer child stroke
                                  clear values (detail-after name args values))))
                             (when marker-p
                               (setf attribution-active t attribution-marker id
                                     attribution-parent subpart
                                     attribution-buffer buffer
                                     attribution-child child
                                     attribution-stroke id)
                               (emit-interval-begin id subpart buffer child id))
                             (values-list values))
                         (apply original args))
                     (unless completed
                       (emit-call-abort name id prior-parent subpart buffer child
                                        stroke clear))
                     (setf current-parent prior-parent
                           current-buffer prior-buffer current-child prior-child
                           current-stroke prior-stroke current-clear prior-clear)))))))
         (install-target (name)
           (let* ((symbol (and owner (find-symbol name owner)))
                  (original (and symbol (fboundp symbol)
                                 (symbol-function symbol))))
             (if (null original)
                 (progn (incf errors) (emit "INSTALL-ERROR name=~S reason=:UNBOUND" name))
               (progn
                 (emit "INSTALL name=~S package=~S original-type=~S"
                       name (package-name (symbol-package symbol))
                       (format nil "~S" (type-of original)))
                 (setf (symbol-function symbol)
                       (let ((target-name name) (target-original original))
                         (lambda (&rest args)
                           (call-wrapper target-name target-original args))))))))
         (count-list (table)
           (mapcar (lambda (name) (list name (gethash name table 0))) targets))
         (finish-main (status)
            (emit "COMPLETE main=~S parents=~D buffers=~D children=~D strokes=~D markers=~D clears=~D predicates=~D global-counts=~S sampled-counts=~S events=~D points=~D cells=~D runs=~D objects=~D checks=~D errors=~D aborts=~D overflow=~S interval-active=~S active=(:parent ~D :buffer ~D :child ~D :stroke ~D :clear ~D)"
                 status parents buffers children strokes markers clears predicates
                 (count-list global-counts) (count-list sampled-counts)
                 events points cells runs objects checks errors aborts overflow
                 attribution-active current-parent current-buffer current-child
                  current-stroke current-clear)
            (emit "END brush-buffer v2")
           (when report (finish-output report) (close report) (setf report nil)))
         )
      (emit "BEGIN brush-buffer v2")
      (emit "CAPS parents=250 buffers=500 children=5000 strokes=5000 markers=250 clears=250 predicates=2000000 events=4000000 points=1000000 cells-per-snapshot=153600 total-cells=150000000 runs=8000000 objects=50000 proper-list=20000 offsets=10000 values=16")
      (dolist (name targets) (install-target name))
      (let* ((main-symbol (and owner (find-symbol "MAIN" owner)))
             (main-original (and main-symbol (fboundp main-symbol)
                                 (symbol-function main-symbol))))
        (if (null main-original)
            (progn (incf errors) (emit "INSTALL-ERROR name=\"MAIN\" reason=:UNBOUND"))
          (progn
            (emit "INSTALL name=\"MAIN\" original-type=~S" 
                  (format nil "~S" (type-of main-original)))
            (setf (symbol-function main-symbol)
                  (lambda (&rest args)
                    (let ((completed nil))
                      (unwind-protect
                          (multiple-value-call
                              (lambda (&rest values)
                                (setf completed t)
                                (safe-log :main-finish
                                  (lambda () (finish-main :normal)))
                                (values-list values))
                            (apply main-original args))
                        (unless completed
                          (safe-log :main-abort
                            (lambda () (finish-main :aborted)))))))))))
      (emit "READY")
      (finish-output report))))
