;;; Complete natural POST-FILL(CFORM) maps; no extra AARON getters.
(in-package :cl-user)
(unless (boundp 'aaron-cform-post-fill-capture-loaded)
  (set 'aaron-cform-post-fill-capture-loaded t)
  (let* ((owner (find-package "COMMON-GRAPHICS-USER"))
         (report (open "C:\\temp\\aaron-cform-post-fill.txt" :direction :output
                       :if-exists :supersede :if-does-not-exist :create))
         (ids (make-hash-table :test #'eq)) (objects 0) (calls 0) (checks 0)
         (readers 0) (cells 0) (runs 0) (errors 0) (aborts 0) (overflow nil) (current nil))
    (labels
        ((emit (control &rest args)
           (when report
             (handler-case
                 (let ((*print-length* nil) (*print-level* nil) (*print-pretty* nil)
                       (*print-circle* nil) (*print-readably* nil))
                   (apply #'format report control args) (terpri report))
               (condition () (incf errors)))))
         (problem (phase condition)
           (incf errors) (emit "ERROR phase=~S type=~S message=~S" phase
                              (format nil "~S" (type-of condition)) (format nil "~A" condition)))
         (limit (kind amount)
           (setf overflow t) (emit "OVERFLOW kind=~S amount=~D" kind amount) (error "CFORM observation cap"))
         (global (name)
           (let ((symbol (find-symbol name owner)))
             (unless (and symbol (boundp symbol)) (error "Missing binding ~A" name)) (symbol-value symbol)))
         (object-id (object)
           (if (null object) 0
             (or (gethash object ids)
                 (let ((id (incf objects)))
                   (when (> objects 2000) (limit :objects objects)) (setf (gethash object ids) id)
                   (emit "OBJECT id=~D type=~S" id (format nil "~S" (type-of object))) id))))
         (snapshot (phase thunk)
           (handler-case
               (let* ((preview (aaron-random-state-preview)) (value (funcall thunk)))
                 (unless (and (eq (car preview) :random-100-1) (equal preview (aaron-random-state-preview)))
                   (error "Observation changed copied random preview")) (incf checks) value)
             (condition (condition) (problem phase condition) nil)))
         (shape (map bits)
           (unless (and (arrayp map) (= (array-rank map) 2)
                        (equal (array-element-type map) (list 'unsigned-byte bits))) (error "Unexpected typed map"))
           (let ((w (array-dimension map 0)) (h (array-dimension map 1)))
             (unless (and (> w 0) (> h 0) (<= (* w h) 153600)) (limit :map (* w h)))
             (list (format nil "~S" (type-of map)) w h bits)))
         (flat (map bits)
           (make-array (array-total-size map) :element-type (list 'unsigned-byte bits) :displaced-to map))
         (map-record (storage dimensions)
           (let* ((w (second dimensions)) (h (third dimensions)) (rows nil) (n 0))
             (when (> (+ cells (* w h)) 160000000) (limit :cells (+ cells (* w h))))
             (dotimes (y h)
               (let ((row nil) (last nil) (count 0))
                 (dotimes (x w)
                   (let ((value (aref storage (+ (* x h) y))))
                     (if (and (> count 0) (= value last)) (incf count)
                       (progn (when (> count 0) (push (list last count) row) (incf n)) (setf last value count 1)))))
                 (when (> count 0) (push (list last count) row) (incf n)) (push (list y (nreverse row)) rows)))
             (incf cells (* w h)) (incf runs n) (when (> runs 8000000) (limit :runs runs))
             (list :shape dimensions :cells (* w h) :covered (* w h) :runs n :rows (nreverse rows))))
         (frame (object)
           (let ((values (list (object-id object))))
             (dolist (name '("LX" "RX" "LY" "TY"))
               (let ((value (slot-value object (find-symbol name owner))))
                 (unless (integerp value) (error "Noninteger frame slot")) (setf values (append values (list value))))) values))
         (before (context)
           (let* ((fill (global "FILL-MAP")) (patch (global "PATCH-MAP"))
                  (fill-shape (shape fill 4)) (patch-shape (shape patch 16)))
             (setf (getf context :fill-object) fill (getf context :patch-object) patch
                   (getf context :fill-shape) fill-shape (getf context :patch-shape) patch-shape
                   (getf context :fill-copy) (copy-seq (flat fill 4)) (getf context :patch-copy) (copy-seq (flat patch 16)))
             (list :background (global "BACKGND") :fill-shape fill-shape :patch-shape patch-shape)))
         (after (context values)
           (unless (and (= (length values) 1) (integerp (car values))) (error "Unsupported POST-FILL result"))
           (let ((fill (global "FILL-MAP")) (patch (global "PATCH-MAP")))
             (list :values values :background (global "BACKGND")
                   :identities (list (eq fill (getf context :fill-object)) (eq patch (getf context :patch-object)))
                   :frames (nreverse (getf context :frames))
                   :patch-read (list (getf context :patch-calls) (getf context :patch-object-id) (getf context :patch-value)
                                     (getf context :patch-value-mismatches) (getf context :patch-argument-mismatches))
                   :maps (list :fill-in (map-record (getf context :fill-copy) (getf context :fill-shape))
                               :patch-in (map-record (getf context :patch-copy) (getf context :patch-shape))
                               :fill-out (map-record (flat fill 4) (shape fill 4))
                               :patch-out (map-record (flat patch 16) (shape patch 16))))))
         (record-frame (args values)
           (unless (and (= (length args) 1) (= (length values) 1)) (error "Unsupported CFRAME arity"))
           (let ((row (list (object-id (car args)) (frame (car values))))) (push row (getf current :frames)) row))
         (record-patch (args values)
           (unless (and (= (length args) 1) (= (length values) 1) (integerp (car values))) (error "Unsupported PATCHDEX arity"))
           (incf readers) (when (> readers 8000000) (limit :readers readers)) (incf (getf current :patch-calls))
           (if (= (getf current :patch-calls) 1)
               (setf (getf current :patch-argument) (car args) (getf current :patch-object-id) (object-id (car args))
                     (getf current :patch-value) (car values))
             (progn (unless (eq (getf current :patch-argument) (car args)) (incf (getf current :patch-argument-mismatches)))
                    (unless (= (getf current :patch-value) (car values)) (incf (getf current :patch-value-mismatches))))))
         (install-reader (name thunk)
           (let* ((symbol (find-symbol name owner)) (original (symbol-function symbol)))
             (emit "INSTALL name=~S type=~S" name (format nil "~S" (type-of original)))
             (setf (symbol-function symbol)
                   (lambda (&rest args)
                     (multiple-value-call
                         (lambda (&rest values)
                           (when current
                             (if (string= name "CFRAME") (snapshot :frame (lambda () (funcall thunk args values)))
                               (handler-case (funcall thunk args values) (condition (condition) (problem :patch-reader condition)))))
                           (values-list values)) (apply original args))))))
         (finish (status)
           (emit "COMPLETE main=~S calls=~D objects=~D checks=~D readers=~D cells=~D runs=~D errors=~D aborts=~D overflow=~S active=~S"
                 status calls objects checks readers cells runs errors aborts overflow (not (null current)))
           (emit "END cform-post-fill v2") (finish-output report) (close report) (setf report nil)))
      (emit "BEGIN cform-post-fill v2")
      (emit "CAPS calls=250 objects=2000 map=153600 cells=160000000 runs=8000000 readers=8000000")
      (install-reader "CFRAME" #'record-frame) (install-reader "PATCHDEX" #'record-patch)
      (let* ((symbol (find-symbol "POST-FILL" owner)) (original (symbol-function symbol)))
        (emit "INSTALL name=~S type=~S" "POST-FILL" (format nil "~S" (type-of original)))
        (setf (symbol-function symbol)
              (lambda (&rest args)
                (if (or (null report) (not (eq (first args) (find-symbol "CFORM" owner)))) (apply original args)
                  (let* ((id (incf calls)) (prior current) (completed nil)
                         (context (list :id id :frames nil :patch-calls 0 :patch-object-id 0 :patch-value nil
                                        :patch-value-mismatches 0 :patch-argument-mismatches 0 :patch-argument nil
                                        :fill-object nil :patch-object nil :fill-shape nil :patch-shape nil
                                        :fill-copy nil :patch-copy nil)))
                    (when (or current (> id 250)) (limit :call id)) (setf current context)
                    (emit "CALL id=~D argc=~D cdex=~D sdex=~D before=~S" id (length args)
                          (second args) (third args) (snapshot :before (lambda () (before context))))
                    (unwind-protect
                        (multiple-value-call
                            (lambda (&rest values)
                              (setf completed t) (emit "RETURN id=~D after=~S" id (snapshot :after (lambda () (after context values))))
                              (values-list values)) (apply original args))
                      (unless completed (incf aborts) (emit "ABORT id=~D" id)) (setf current prior)))))))
      (let* ((symbol (find-symbol "MAIN" owner)) (original (symbol-function symbol)))
        (setf (symbol-function symbol)
              (lambda (&rest args)
                (let ((completed nil))
                  (unwind-protect
                      (multiple-value-prog1 (apply original args) (setf completed t) (finish :normal))
                    (unless completed (finish :aborted)))))))
      (emit "READY") (finish-output report))))
