;;; Full bounded inputs/outputs of natural SET-MEDIANS, GOOD-START and
;;; FILL-STRATEGY calls. No additional fill calls or application binding writes.
(in-package :cl-user)

(unless (boundp 'aaron-fill-preparation-capture-loaded)
  (set 'aaron-fill-preparation-capture-loaded t)
  (let* ((owner (find-package "COMMON-GRAPHICS-USER"))
         (report (open "C:\\temp\\aaron-fill-preparation.txt"
                       :direction :output :if-exists :supersede
                       :if-does-not-exist :create))
         (targets '("SET-MEDIANS" "GOOD-START" "FILL-STRATEGY"))
         (calls 0) (fills 0) (errors 0) (aborts 0) (overflow nil) (rng-checks 0)
         (total-points 0) (total-runs 0) (stack nil) (current-fill nil)
         (point-ids nil) (next-point-id 0)
         (counts (make-hash-table :test #'equal)))
    (labels
        ((emit (control &rest args)
           (when report
             (handler-case
                 (let ((*print-length* nil) (*print-level* nil)
                       (*print-pretty* nil) (*print-circle* nil)
                       (*print-readably* nil))
                   (apply #'format report control args)
                   (terpri report))
               (condition () (incf errors)))))
         (mark-error (id phase problem)
           (incf errors)
           (emit "ERROR id=~D phase=~S type=~S" id phase
                 (format nil "~S" (type-of problem))))
         (limit-error (kind amount)
           (setf overflow t)
           (emit "OVERFLOW kind=~S amount=~D" kind amount)
           (error "Fill preparation observation cap"))
         (global (name)
           (let ((symbol (find-symbol name owner)))
             (unless (and symbol (boundp symbol))
               (error "Missing required observation binding"))
             (symbol-value symbol)))
         (binding (name)
           (let ((symbol (find-symbol name owner)))
             (if (and symbol (boundp symbol))
                 (let ((value (symbol-value symbol)))
                   (unless (integerp value) (error "Expected integer binding"))
                   (list :bound t :value value))
               (list :bound nil))))
         (getter (name object)
           (let ((symbol (find-symbol name owner)))
             (unless (and symbol (fboundp symbol)) (error "Missing getter"))
             (let ((values (multiple-value-list
                            (funcall (symbol-function symbol) object))))
               (unless (and (= (length values) 1) (integerp (car values)))
                 (error "Expected one integer getter value"))
               (car values))))
         (frame (object)
           (list :type (format nil "~S" (type-of object))
                 :ly (getter "LY" object) :ty (getter "TY" object)))
         (list-ids (value)
           (let ((rest value) (ids nil) (seen (make-hash-table :test #'eq))
                 (count 0))
             (do () ((not (consp rest)))
               (when (gethash rest seen) (error "Cyclic outline"))
               (setf (gethash rest seen) t)
               (when (>= count 10000) (limit-error :list-points count))
               (let ((id (gethash (car rest) point-ids)))
                 (unless id
                   (setf id (incf next-point-id)
                         (gethash (car rest) point-ids) id))
                 (push id ids))
               (incf count)
               (setf rest (cdr rest)))
             (unless (null rest) (error "Improper outline"))
             (nreverse ids)))
         (outline (value)
           (let ((ids (list-ids value)) (rest value) (points nil))
             (incf total-points (length ids))
             (when (> total-points 1000000)
               (limit-error :total-points total-points))
             (dolist (id ids)
               (let ((point (car rest)))
                 (push (list id (format nil "~S" (type-of point))
                             (getter "X" point) (getter "Y" point)) points))
               (setf rest (cdr rest)))
             (list :length (length ids) :complete t :points (nreverse points))))
         (region (points dimensions lo hi)
           (let* ((width (first dimensions)) (height (second dimensions))
                  (x0 (1- width)) (x1 0) (y0 lo) (y1 hi))
             (unless (and (integerp width) (integerp height)
                          (> width 0) (> height 0)) (error "Invalid dimensions"))
             (if (null points)
                 (list 0 (1- width) 0 (1- height) (* width height))
               (progn
                 (dolist (point points)
                   (let ((x (third point)) (y (fourth point)))
                     (unless (and (<= 0 x) (< x width) (<= 0 y) (< y height))
                       (error "Outline outside map"))
                     (setf x0 (min x0 x) x1 (max x1 x)
                           y0 (min y0 y) y1 (max y1 y))))
                 (setf x0 (max 0 (1- x0)) x1 (min (1- width) (1+ x1))
                       y0 (max 0 (1- y0)) y1 (min (1- height) (1+ y1)))
                 (list x0 x1 y0 y1
                       (* (1+ (- x1 x0)) (1+ (- y1 y0))))))))
         (map-snapshot (map points lo hi)
           (unless (and (arrayp map) (= (array-rank map) 2))
             (error "Expected rank-two map"))
           (let* ((dimensions (array-dimensions map))
                  (bounds (region points dimensions lo hi))
                  (x0 (first bounds)) (x1 (second bounds))
                  (y0 (third bounds)) (y1 (fourth bounds))
                  (cells (fifth bounds)) (rows nil) (runs 0))
             (when (> cells 153600) (limit-error :map-cells cells))
             (dotimes (row-offset (1+ (- y1 y0)))
               (let ((y (+ y0 row-offset)) (row nil) (value nil) (count 0))
                 (dotimes (column-offset (1+ (- x1 x0)))
                   (let ((next (aref map (+ x0 column-offset) y)))
                     (unless (and (integerp next) (<= 0 next) (<= next 15))
                       (error "Invalid four-bit map cell"))
                     (if (and (> count 0) (= value next))
                         (incf count)
                       (progn
                         (when (> count 0) (push (list value count) row) (incf runs))
                         (setf value next count 1)))))
                 (when (> count 0) (push (list value count) row) (incf runs))
                 (push (list y :runs (nreverse row)) rows)))
             (incf total-runs runs)
             (when (> total-runs 2000000) (limit-error :map-runs total-runs))
             (list :type (format nil "~S" (type-of map))
                   :dimensions dimensions :element-type (array-element-type map)
                   :region bounds :cells cells :covered cells :runs runs
                   :complete t :rows (nreverse rows))))
         (snapshot (name args)
           (let ((state (list :lo (binding "LO-MEDIAN") :hi (binding "HI-MEDIAN")))
                 (out nil) (map nil))
             (cond
               ((string= name "SET-MEDIANS")
                (unless (= (length args) 1) (error "Unexpected frame arguments"))
                (setf state (append state (list :frame (frame (car args))))))
               (t
                (unless (null args) (error "Unexpected helper arguments"))
                (setf out (global "OUT-LIST"))
                (let ((record (outline out)))
                  (setf state (append state (list :outline record)))
                  (when (string= name "FILL-STRATEGY")
                    (setf map (global "FILL-MAP"))
                    (setf state
                          (append state
                                  (list :map (map-snapshot
                                              map (getf record :points)
                                              (global "LO-MEDIAN")
                                              (global "HI-MEDIAN")))))))))
             (list state out map)))
         (safe-snapshot (id phase name args)
           (handler-case
               (let* ((preview (aaron-random-state-preview))
                      (result (snapshot name args)))
                 (unless (and (eq (car preview) :random-100-1)
                              (equal preview (aaron-random-state-preview)))
                   (error "Observation changed copied random-state preview"))
                 (incf rng-checks)
                 result)
             (condition (problem)
               (mark-error id phase problem)
               (list (list :observation-error t) nil nil))))
         (return-record (values after-out)
           (when (> (length values) 16) (limit-error :values (length values)))
           (mapcar (lambda (value)
                     (cond ((null value) nil)
                           ((integerp value) value)
                           ((consp value)
                            (list :list-ids (list-ids value)
                                  :eq-outline (eq value after-out)))
                           (t (error "Unexpected helper return")))) values))
         (install-helper (name)
           (let* ((symbol (find-symbol name owner))
                  (original (and symbol (fboundp symbol) (symbol-function symbol))))
             (unless original (error "Missing helper"))
             (emit "INSTALL name=~S type=~S" name (format nil "~S" (type-of original)))
             (setf (symbol-function symbol)
                   (lambda (&rest args)
                     (if (or (null report) overflow (>= calls 2000))
                         (progn
                           (when (and report (not overflow))
                             (setf overflow t) (emit "OVERFLOW kind=:CALLS amount=~D" calls))
                           (apply original args))
                       (let* ((id (incf calls)) (completed nil)
                              (before (safe-snapshot id :before name args)))
                         (incf (gethash name counts 0))
                         (unless current-fill (mark-error id :outside-fill :missing))
                         (push id stack)
                         (emit "CALL id=~D fill=~D name=~S before=~S"
                               id (or current-fill 0) name (first before))
                         (unwind-protect
                             (multiple-value-call
                                 (lambda (&rest values)
                                   (setf completed t)
                                   (let* ((after (safe-snapshot id :after name args))
                                          (state (append (first after)
                                                         (list :outline-eq-entry
                                                               (eq (second before) (second after))
                                                               :map-eq-entry
                                                               (eq (third before) (third after))))))
                                     (handler-case
                                         (emit "RETURN id=~D values=~S after=~S"
                                               id (return-record values (second after)) state)
                                       (condition (problem) (mark-error id :return problem))))
                                   (pop stack)
                                   (values-list values))
                               (apply original args))
                           (unless completed
                             (incf aborts)
                             (emit "ABORT id=~D" id)
                             (pop stack)))))))))
         (install-my ()
           (let* ((symbol (find-symbol "MY-FILL" owner))
                  (original (symbol-function symbol)))
             (emit "INSTALL name=~S type=~S" "MY-FILL" (format nil "~S" (type-of original)))
             (setf (symbol-function symbol)
                   (lambda (&rest args)
                     (if (or (null report) overflow (>= fills 500))
                         (progn
                           (when (and report (not overflow))
                             (setf overflow t) (emit "OVERFLOW kind=:FILLS amount=~D" fills))
                           (apply original args))
                       (let ((id (incf fills)) (prior current-fill)
                             (prior-ids point-ids) (prior-next next-point-id)
                             (completed nil))
                         (setf current-fill id point-ids (make-hash-table :test #'eq)
                               next-point-id 0)
                         (emit "FILL id=~D mode=~S cdex=~D sdex=~D"
                               id (symbol-name (first args)) (second args) (third args))
                         (unwind-protect
                             (multiple-value-call
                                 (lambda (&rest values)
                                   (setf completed t)
                                   (handler-case
                                       (emit "END-FILL id=~D values=~S" id (return-record values nil))
                                     (condition (problem) (mark-error id :fill-return problem)))
                                   (values-list values))
                               (apply original args))
                           (unless completed (incf aborts) (emit "ABORT-FILL id=~D" id))
                           (setf current-fill prior point-ids prior-ids next-point-id prior-next))))))))
         (finish (status)
           (dolist (name targets) (emit "TOTAL name=~S calls=~D" name (gethash name counts 0)))
           (emit "COMPLETE main=~S calls=~D fills=~D points=~D runs=~D rng-checks=~D errors=~D aborts=~D overflow=~S depth=~D"
                 status calls fills total-points total-runs rng-checks errors aborts overflow (length stack))
           (emit "END fill-preparation v1")
           (when report (finish-output report) (close report) (setf report nil))))
      (emit "BEGIN fill-preparation v1")
      (emit "CAPS calls=2000 fills=500 list-points=10000 total-points=1000000 map-cells=153600 map-runs=2000000 values=16")
      (dolist (name targets) (install-helper name))
      (install-my)
      (let* ((symbol (find-symbol "MAIN" owner)) (original (symbol-function symbol)))
        (emit "INSTALL name=~S type=~S" "MAIN" (format nil "~S" (type-of original)))
        (setf (symbol-function symbol)
              (lambda (&rest args)
                (let ((completed nil))
                  (unwind-protect
                      (multiple-value-prog1 (apply original args)
                        (setf completed t) (finish :normal))
                    (unless completed (finish :aborted)))))))
      (emit "READY"))))
