;;; Exploratory FREE-PATH call with private point lists and dynamic globals.
;;; RAN/POL-VPT wrappers call the original functions and cap dependency calls;
;;; unwrapped baseline parity is a separate follow-up, not assumed here.
(in-package :cl-user)
(unless (boundp 'aaron-free-path-behavior-loaded)
  (set 'aaron-free-path-behavior-loaded t)
  (with-open-file (report "C:\\temp\\aaron-free-path-behavior.txt"
                          :direction :output :if-exists :supersede
                          :if-does-not-exist :create)
    (let* ((*print-length* nil) (*print-level* 10) (*print-pretty* nil)
           (owner (find-package "COMMON-GRAPHICS-USER"))
           (make (find-symbol "MAKE-VISPT" owner))
           (ran (find-symbol "RAN" owner))
           (pol (find-symbol "POL-VPT" owner))
           (original-ran (symbol-function ran))
           (original-pol (symbol-function pol))
           (factory (find-symbol "MAKE-RANDOM-STATE-FROM-SEED" "EXCL")))
      (labels ((point (value)
                 (list (funcall (find-symbol "X" owner) value)
                       (funcall (find-symbol "Y" owner) value)
                       (funcall (find-symbol "VIS" owner) value)))
               (shape (value &optional (depth 0))
                 (cond ((or (numberp value) (symbolp value)) value)
                       ((and (consp value) (< depth 256))
                        (cons (shape (car value) 256) (shape (cdr value) (1+ depth))))
                       (t (handler-case (list :point (point value))
                            (error () (list :type (type-of value)))))))
               (problem (value)
                 (format report "ERROR ~S~%" (type-of value))
                 (when (typep value 'type-error)
                   (format report "TYPE-DATUM ~S~%EXPECTED-TYPE ~S~%"
                           (shape (type-error-datum value)) (shape (type-error-expected-type value))))
                 (when (typep value 'cell-error)
                   (format report "CELL ~S~%" (cell-error-name value)))
                 (handler-case
                     (let ((control (simple-condition-format-control value)))
                       (when (stringp control)
                         (format report "CONTROL ~S~%" (subseq control 0 (min 512 (length control))))))
                   (error () nil))))
        (format report "BEGIN free-path-behavior~%")
        (format report "INTERVENTION BOUNDED-RAN-POL-VPT-WRAPPERS~%")
        (format report "MAKE-ARGLIST ~S~%" (funcall (find-symbol "ARGLIST" "EXCL") make))
        (dolist (name '("FDEX" "TDEX" "FROM" "TO"))
          (let ((symbol (find-symbol name owner)))
            (format report "GLOBAL ~S bound=~S" name (boundp symbol))
            (when (boundp symbol) (format report " value=~S" (shape (symbol-value symbol))))
            (terpri report)))
        (finish-output report)
        (unwind-protect
            (dolist (seed '(1 1234))
              (dolist (visible '(nil t))
                (dolist (bounds '(((0 0) (10 0)) ((0 0) (100 0)) ((2 3) (12 18))))
                  (let ((*random-state* (funcall factory seed)) (calls 0))
                    (format report "TRY seed=~D vis=~S bounds=~S~%" seed visible bounds)
                    (finish-output report)
                    (setf (symbol-function ran)
                          (lambda (a b)
                            (when (> (incf calls) 2048) (error "Dependency call bound"))
                            (let ((value (funcall original-ran a b)))
                              (format report "RAN (~S ~S) => ~S~%" a b value)
                              value)))
                    (setf (symbol-function pol)
                          (lambda (pt a d v)
                            (when (> (incf calls) 2048) (error "Dependency call bound"))
                            (let ((value (funcall original-pol pt a d v)))
                              (format report "POL-VPT ~S ~S ~S ~S => ~S~%"
                                      (point pt) a d v (point value))
                              value)))
                    (progv (mapcar (lambda (name) (find-symbol name owner))
                                   '("FDEX" "TDEX" "FROM" "TO"))
                           '(0 1 0 1)
                      (handler-case
                          (let ((edge (mapcar (lambda (xy) (funcall make (car xy) (cadr xy) visible)) bounds)))
                            (format report "CONSTRUCTED ~S~%" (shape edge))
                            (finish-output report)
                            (let ((result (funcall (find-symbol "FREE-PATH" owner) edge)))
                              (format report "RESULT ~S~%" (shape result))
                              (format report "EDGE-AFTER ~S~%" (shape edge))))
                        (error (value) (problem value)))
                      (dolist (name '("FDEX" "TDEX" "FROM" "TO"))
                        (format report "AFTER ~S ~S~%" name (shape (symbol-value (find-symbol name owner))))))
                    (format report "NEXT-RANDOM ~S~%CALLS ~D~%ENDCASE~%" (random 1000) calls)
                    (finish-output report)))))
          (setf (symbol-function ran) original-ran)
          (setf (symbol-function pol) original-pol))
        (format report "RESTORED ~S~%"
                (and (eq (symbol-function ran) original-ran) (eq (symbol-function pol) original-pol)))
        (format report "END free-path-behavior~%")
        (finish-output report)))))
