;;; Compare traced FREE-PATH against unwrapped baselines after dispatch warmup.
;;; Inputs are fresh private VISPT lists; globals and function bindings restore.
(in-package :cl-user)
(unless (boundp 'aaron-free-path-validation-loaded)
  (set 'aaron-free-path-validation-loaded t)
  (with-open-file (report "C:\\temp\\aaron-free-path-validation.txt"
                          :direction :output :if-exists :supersede
                          :if-does-not-exist :create)
    (let* ((*print-length* nil) (*print-level* 12) (*print-pretty* nil)
           (owner (find-package "COMMON-GRAPHICS-USER"))
           (make (find-symbol "MAKE-VISPT" owner))
           (ran (find-symbol "RAN" owner)) (pol (find-symbol "POL-VPT" owner))
           (dist (find-symbol "XYDIST" owner))
           (original-ran (symbol-function ran)) (original-pol (symbol-function pol))
           (original-dist (symbol-function dist))
           (factory (find-symbol "MAKE-RANDOM-STATE-FROM-SEED" "EXCL"))
           (tracing nil) (calls 0))
      (labels ((point (value)
                 (list (funcall (find-symbol "X" owner) value)
                       (funcall (find-symbol "Y" owner) value)
                       (funcall (find-symbol "VIS" owner) value)))
               (measure (points seed)
                 (let ((*random-state* (funcall factory seed)))
                   (setf calls 0)
                   (progv (mapcar (lambda (name) (find-symbol name owner))
                                  '("FDEX" "TDEX" "FROM" "TO"))
                          (list 0 (1- (length points)) 0 1)
                     (let* ((edge (mapcar (lambda (p) (apply make p)) points))
                            (path (funcall (find-symbol "FREE-PATH" owner) edge)))
                       (list (mapcar #'point path) (mapcar #'point edge) (random 1000))))))
               (tick ()
                 (when (> (incf calls) 2048) (error "Dependency call bound")))
               (restore ()
                 (setf (symbol-function ran) original-ran)
                 (setf (symbol-function pol) original-pol)
                 (setf (symbol-function dist) original-dist)))
        (format report "BEGIN free-path-validation~%")
        (dolist (seed '(1 5489))
          (dolist (points '(((0 0 1) (10 0 1))
                            ((17 -9 1) (17 34 1))
                            ((-23 41 1) (-51 -7 1))
                            ((1.25d0 -2.5d0 1) (19.75d0 7.125d0 1))
                            ((0 0 0) (10 0 1) (10 10 0))
                            ((0 0 1) (10 0 1) (10 10 1))
                            ((0 0 2) (10 0 2))
                            ((0 0 -1) (10 0 -1))))
            (format report "TRY seed=~D points=~S~%" seed points)
            (finish-output report)
            (unwind-protect
                (handler-case
                    (progn
                      (setf (symbol-function ran)
                            (lambda (a b)
                              (tick)
                              (let ((value (funcall original-ran a b)))
                                (when tracing (format report "RAN (~S ~S) => ~S~%" a b value))
                                value)))
                      (setf (symbol-function pol)
                            (lambda (pt a d v)
                              (tick)
                              (let ((value (funcall original-pol pt a d v)))
                                (when tracing
                                  (format report "POL-VPT ~S ~S ~S ~S => ~S~%" (point pt) a d v (point value)))
                                value)))
                      (setf (symbol-function dist)
                            (lambda (a b)
                              (tick)
                              (let ((value (funcall original-dist a b)))
                                (when tracing (format report "XYDIST ~S ~S => ~S~%" (point a) (point b) value))
                                value)))
                      ;; Warm all wrappers with this input before resetting the seed.
                      (setf tracing nil)
                      (measure points seed)
                      (format report "WARMED~%")
                      (setf tracing t)
                      (let ((actual (measure points seed)))
                        (format report "ACTUAL ~S~%CALLS ~D~%" actual calls)
                        (setf tracing nil)
                        (restore)
                        (measure points seed)
                        (let ((baseline (measure points seed)))
                          (format report "BASELINE ~S~%MATCH ~S~%" baseline (equalp baseline actual)))))
                  (error (problem)
                    (format report "ERROR ~S~%" (type-of problem))))
              (setf tracing nil)
              (restore))
            (format report "ENDCASE~%")
            (finish-output report)))
        (format report "RESTORED ~S~%"
                (and (eq (symbol-function ran) original-ran)
                     (eq (symbol-function pol) original-pol)
                     (eq (symbol-function dist) original-dist)))
        (format report "END free-path-validation~%")
        (finish-output report)))))
