;;; Measure INIT-MAPS in private dynamic bindings only.
;;; No shared map, brush, fill, or drawing routine is invoked.
(in-package :cl-user)

;; Keep BEGIN in its own top-level form.  This leaves a durable checkpoint if
;; compilation/loading of the behavioral form fails before the call begins.
(with-open-file (report "C:\\temp\\aaron-init-maps.txt"
                        :direction :output :if-exists :supersede
                        :if-does-not-exist :create)
  (format report "BEGIN init-maps~%")
  (finish-output report))

(with-open-file (report "C:\\temp\\aaron-init-maps.txt"
                        :direction :output :if-exists :append
                        :if-does-not-exist :create)
  (let ((current-cell "setup"))
    (labels
        ((emit (control &rest arguments)
           (apply #'format report control arguments)
           (finish-output report))
         (snapshot (symbol)
           (list symbol (boundp symbol)
                 (and (boundp symbol) (symbol-value symbol))))
         (same-binding-p (saved)
           (let ((symbol (first saved))
                 (was-bound (second saved))
                 (old-value (third saved)))
             (and (eql was-bound (boundp symbol))
                  (or (not was-bound)
                      (eq old-value (symbol-value symbol))))))
         (describe-binding (label symbol)
           (if (boundp symbol)
               (emit "BEFORE ~A BOUNDP=T TYPE=~S~%"
                     label (type-of (symbol-value symbol)))
               (emit "BEFORE ~A BOUNDP=NIL~%" label)))
         (map-summary (label symbol)
           (setf current-cell label)
           (if (boundp symbol)
               (let ((value (symbol-value symbol)))
                 (if (arrayp value)
                     (let ((total (array-total-size value)))
                       (emit "MAP ~A BOUNDP=T ARRAYP=T TYPE=~S RANK=~S DIMS=~S ELEMENT-TYPE=~S TOTAL=~S~%"
                             label (type-of value) (array-rank value)
                             (array-dimensions value) (array-element-type value)
                             total)
                       (if (<= total 256)
                           (dotimes (index total)
                             (setf current-cell (format nil "~A[~D]" label index))
                             (emit "CELL ~A ~S~%" current-cell
                                   (row-major-aref value index)))
                           (emit "UNEXPECTED-SIZE ~A TOTAL=~S~%" label total)))
                     (emit "MAP ~A BOUNDP=T ARRAYP=NIL TYPE=~S~%"
                           label (type-of value))))
               (emit "MAP ~A BOUNDP=NIL~%" label)))
         (run-case (width height repeat-p)
           (let* ((user (find-package "COMMON-GRAPHICS-USER"))
                  (wide-symbol (find-symbol "*PIC-WIDE*" user))
                  (high-symbol (find-symbol "*PIC-HIGH*" user))
                  (patch-symbol (find-symbol "PATCH-MAP" user))
                  (fill-symbol (find-symbol "FILL-MAP" user))
                  (init-symbol (find-symbol "INIT-MAPS" user))
                  (symbols (list wide-symbol high-symbol patch-symbol fill-symbol))
                  (saved (mapcar #'snapshot symbols)))
             (unless (every #'symbolp symbols)
               (error "INIT-MAPS symbol lookup failed: ~S" symbols))
             (emit "CASE WIDTH=~S HEIGHT=~S~%" width height)
             (describe-binding "*PIC-WIDE*" wide-symbol)
             (describe-binding "*PIC-HIGH*" high-symbol)
             (describe-binding "PATCH-MAP" patch-symbol)
             (describe-binding "FILL-MAP" fill-symbol)
             (handler-case
                 (unwind-protect
                     (progv symbols (list width height nil nil)
                       (unless (and init-symbol (fboundp init-symbol))
                         (error "INIT-MAPS is not callable"))
                       (setf current-cell "INIT-MAPS")
                       (multiple-value-bind (returned secondary) (funcall (symbol-function init-symbol))
                         (declare (ignore secondary))
                         (emit "INIT-RETURN TYPE=~S EQ-PATCH=~S EQ-FILL=~S~%"
                               (type-of returned)
                               (eq returned (and (boundp patch-symbol)
                                                (symbol-value patch-symbol)))
                               (eq returned (and (boundp fill-symbol)
                                                (symbol-value fill-symbol)))))
                       (map-summary "PATCH-MAP" patch-symbol)
                       (map-summary "FILL-MAP" fill-symbol)
                       (emit "MAP-EQ ~S~%"
                             (and (boundp patch-symbol) (boundp fill-symbol)
                                  (eq (symbol-value patch-symbol)
                                      (symbol-value fill-symbol))))
                       (when repeat-p
                         (let ((first-patch (and (boundp patch-symbol)
                                                 (symbol-value patch-symbol)))
                               (first-fill (and (boundp fill-symbol)
                                                (symbol-value fill-symbol))))
                           (setf current-cell "INIT-MAPS-SECOND-CALL")
                           (funcall (symbol-function init-symbol))
                           (let ((second-patch (and (boundp patch-symbol)
                                                    (symbol-value patch-symbol)))
                                 (second-fill (and (boundp fill-symbol)
                                                   (symbol-value fill-symbol))))
                             (emit "REINIT PATCH-REUSED=~S PATCH-REPLACED=~S FILL-REUSED=~S FILL-REPLACED=~S~%"
                                   (eq first-patch second-patch)
                                   (not (eq first-patch second-patch))
                                   (eq first-fill second-fill)
                                   (not (eq first-fill second-fill)))
                             (map-summary "PATCH-MAP-SECOND" patch-symbol)
                             (map-summary "FILL-MAP-SECOND" fill-symbol)))))
                   (emit "RESTORED T~%"))
               (error (problem)
                 (emit "ERROR CELL=~A TYPE=~S~%" current-cell (type-of problem))))
             (emit "BINDINGS-RESTORED ~S~%"
                   (every #'same-binding-p saved)))))
      (emit "INTERVENTION PRIVATE-DYNAMIC-BINDINGS~%")
      (finish-output report)
      (run-case 3 5 t)
      (run-case 5 3 nil)
      (run-case 1 1 nil)
      (emit "END init-maps~%"))))
