;;; Opt-in RAN trace only while a natural FREE-PATH call is active.
;;; Load after the seeded scene trace and natural-free-path-capture.cl.
(in-package :cl-user)

(unless (boundp 'aaron-natural-free-path-ran-capture-loaded)
  (let* ((owner (find-package "COMMON-GRAPHICS-USER"))
         (free-path (and owner (find-symbol "FREE-PATH" owner)))
         (ran (and owner (find-symbol "RAN" owner)))
         (report (open "C:\\temp\\aaron-free-path-ran.txt"
                       :direction :output :if-exists :supersede
                       :if-does-not-exist :create))
         (call-id 0)
         (active-id nil)
         (ran-ordinal 0)
         (call-limit 16)
         (ran-limit 1024)
         (ran-overflow-written nil))
    (labels ((emit (control &rest arguments)
               (let ((*print-length* 12)
                     (*print-level* 6)
                     (*print-pretty* nil))
                 (apply #'format report control arguments)
                 (terpri report)
                 (finish-output report)))
             (typed (value)
               (if (numberp value)
                   (list :type (type-of value) :value value)
                 (list :type (type-of value))))
             (preview ()
               (let ((copy (make-random-state *random-state*)))
                 (list (random 100 copy)
                       (random 100 copy)
                       (random 100 copy)))))
      (emit "BEGIN natural-free-path-ran v1")
      (emit "CAPS free-path-calls=~D ran-calls=~D" call-limit ran-limit)
      (if (and free-path ran (fboundp free-path) (fboundp ran))
          (let ((original-free-path (symbol-function free-path))
                (original-ran (symbol-function ran)))
            (setf (symbol-function ran)
                  (lambda (&rest args)
                    (if (null active-id)
                        (apply original-ran args)
                      (let ((ordinal (incf ran-ordinal)))
                        (when (and (> ordinal ran-limit)
                                   (not ran-overflow-written))
                          (setf ran-overflow-written t)
                          (emit "OVERFLOW ran-calls first-omitted=~D" ordinal))
                        (multiple-value-call
                            (lambda (&rest results)
                              (when (<= ordinal ran-limit)
                                (emit "RAN free-path-id=~D ordinal=~D args=~S values=~S"
                                      active-id ordinal
                                      (mapcar #'typed args)
                                      (mapcar #'typed results)))
                              (values-list results))
                          (apply original-ran args))))))
            (setf (symbol-function free-path)
                  (lambda (&rest args)
                    (let* ((id (incf call-id))
                           (prior active-id)
                           (record-p (<= id call-limit))
                           (ran-before ran-ordinal))
                      (when record-p
                        (emit "CALL id=~D arg-count=~D rng-before=~S"
                              id (length args) (preview)))
                      (setf active-id id)
                      (unwind-protect
                          (multiple-value-call
                              (lambda (&rest results)
                                (when record-p
                                  (emit "RETURN id=~D value-count=~D ran-count=~D rng-after=~S"
                                        id (length results)
                                        (- ran-ordinal ran-before) (preview)))
                                (values-list results))
                            (apply original-free-path args))
                        (setf active-id prior)))))
            (emit "READY free-path=~S ran=~S" free-path ran))
        (emit "INSTALL-ERROR free-path=~S ran=~S" free-path ran)))
    (set 'aaron-natural-free-path-ran-capture-loaded t)))
