;;; Read-only colour and fill-map samples around natural screen paths.
;;; Load after the full writer and screen-unit observers. The original call is
;;; always forwarded with its arguments and multiple values unchanged.
(in-package :cl-user)

(unless (boundp 'aaron-natural-screen-color-capture-loaded)
  (let* ((owner (find-package "COMMON-GRAPHICS-USER"))
         (target (and owner (find-symbol "SCREEN-AND-STORE" owner)))
         (x-reader (and owner (find-symbol "X" owner)))
         (y-reader (and owner (find-symbol "Y" owner)))
         (report (open "C:\\temp\\aaron-screen-color-data.txt"
                       :direction :output :if-exists :supersede
                       :if-does-not-exist :create))
         (call-count 0)
         (call-limit 8)
         (point-limit 128)
         (color-limit 64)
         (slot-count-limit 3)
         (overflow-written nil)
         (end-written nil)
         (value-depth-limit 3))
    (labels ((emit (control &rest arguments)
               (let ((*print-length* 24)
                     (*print-level* 8)
                     (*print-pretty* nil)
                     (*print-circle* t))
                 (apply #'format report control arguments)
                 (terpri report)
                 (finish-output report)))
             (safe-value (value &optional (depth 0))
               (handler-case
                   (cond
                     ((numberp value) (list :number (type-of value) value))
                     ((symbolp value) (list :symbol (symbol-package value)
                                            (symbol-name value)))
                     ((stringp value) (list :string-length (length value)))
                     ((and (consp value) (< depth value-depth-limit))
                      (let ((rest value) (items nil) (count 0))
                        (do () ((or (null rest) (not (consp rest)) (>= count 8)))
                          (push (safe-value (car rest) (1+ depth)) items)
                          (setf rest (cdr rest))
                          (incf count))
                        (list :cons (nreverse items)
                              :tail (cond ((null rest) :nil)
                                          ((consp rest) :more)
                                          (t (type-of rest))))))
                     ((consp value) :cons-depth-limit)
                     ((arrayp value) (list :array (array-rank value)
                                           (array-dimensions value)))
                     (t (list :object (type-of value))))
                 (condition (problem)
                   (list :summary-error (type-of problem)))))
             (find-helper (package-name symbol-name)
               (let* ((package (find-package package-name))
                      (symbol (and package (find-symbol symbol-name package))))
                 (and symbol (fboundp symbol) (symbol-function symbol))))
             (list-count-at-most (value limit)
               (let ((rest value) (count 0))
                 (do () ((or (null rest) (not (consp rest)) (>= count limit)))
                   (setf rest (cdr rest))
                   (incf count))
                 count))
             (object-fields (object)
               (handler-case
                   (let* ((class-slots (find-helper "CLOS" "CLASS-SLOTS"))
                          (slot-name (or (find-helper "CLOS" "SLOT-DEFINITION-NAME")
                                         (find-helper "CLOS" "SLOT-NAME")))
                          (slot-reader (find-helper "COMMON-LISP" "SLOT-VALUE"))
                          (class (class-of object)))
                     (if (and class-slots slot-name slot-reader)
                         (let ((slots (funcall class-slots class))
                               (items nil) (count 0))
                           (dolist (slot slots)
                             (when (< count slot-count-limit)
                               (let* ((name (funcall slot-name slot))
                                      (value (handler-case
                                                 (funcall slot-reader object name)
                                               (condition (problem)
                                                 (list :read-error (type-of problem))))))
                                 (push (list name (safe-value value)) items)
                                 (incf count))))
                           (list :class (class-name class)
                                 :fields (nreverse items)
                                 :truncated (> (length slots) slot-count-limit)))
                       (list :class (class-name class) :fields-unavailable t)))
                 (condition (problem)
                   (list :field-error (type-of problem)))))
             (emit-colors ()
               (handler-case
                   (let* ((symbol (and owner (find-symbol "RGB-MAP" owner)))
                          (colors (and symbol (boundp symbol) (symbol-value symbol)))
                          (rest colors) (index 0))
                     (emit "COLORS-BEGIN count-at-least=~D"
                           (list-count-at-most colors (1+ color-limit)))
                     (do () ((or (null rest) (not (consp rest))
                                 (>= index color-limit)))
                       (emit "COLOR index=~D type=~S fields=~S"
                             index (type-of (car rest)) (object-fields (car rest)))
                       (setf rest (cdr rest))
                       (incf index))
                     (emit "COLORS-END shown=~D tail=~A" index
                           (if (null rest) "NIL" (type-of rest))))
                 (condition (problem)
                   (emit "COLORS-ERROR type=~A" (type-of problem)))))
             (map-points (phase id path)
               (handler-case
                   (let* ((map-symbol (and owner (find-symbol "FILL-MAP" owner)))
                          (map (and map-symbol (boundp map-symbol)
                                    (symbol-value map-symbol)))
                          (rest path) (index 0))
                     (unless (and (arrayp map) (= (array-rank map) 2)
                                  x-reader y-reader (fboundp x-reader)
                                  (fboundp y-reader))
                       (emit "MAP-UNAVAILABLE phase=~A call=~D map-type=~A"
                             phase id (if map (type-of map) "UNBOUND"))
                       (return-from map-points nil))
                     (do () ((or (null rest) (not (consp rest))
                                 (>= index point-limit)))
                       (let* ((point (car rest))
                              (px (funcall (symbol-function x-reader) point))
                              (py (funcall (symbol-function y-reader) point))
                              (xy (handler-case
                                      (if (and (<= 0 px) (< px (array-dimension map 0))
                                               (<= 0 py) (< py (array-dimension map 1)))
                                          (safe-value (aref map px py))
                                        :out-of-bounds)
                                    (condition (problem)
                                      (list :read-error (type-of problem)))))
                              (yx (handler-case
                                      (if (and (<= 0 py) (< py (array-dimension map 0))
                                               (<= 0 px) (< px (array-dimension map 1)))
                                          (safe-value (aref map py px))
                                        :out-of-bounds)
                                    (condition (problem)
                                      (list :read-error (type-of problem)))))
                              (rplane-symbol (and owner (find-symbol "RPLANE" owner)))
                              (rplane (and rplane-symbol (boundp rplane-symbol)
                                           (symbol-value rplane-symbol))))
                         (emit "MAPPOINT phase=~A call=~D point=~D xy=(~D ~D) rplane=~S xy-value=~S yx-value=~S"
                               phase id index px py (safe-value rplane) xy yx))
                       (setf rest (cdr rest))
                       (incf index))
                     (when (and rest (>= index point-limit))
                       (emit "MAP-OVERFLOW phase=~A call=~D first-omitted-point=~D"
                             phase id index)))
                 (condition (problem)
                   (emit "MAP-ERROR phase=~A call=~D type=~A"
                         phase id (type-of problem)))))
             (state-token (name)
               (handler-case
                   (let ((symbol (and owner (find-symbol name owner))))
                     (if (and symbol (boundp symbol))
                         (safe-value (symbol-value symbol))
                       :unbound))
                 (condition (problem) (list :error (type-of problem))))))
      (emit "BEGIN natural-screen-color-data v1")
      (emit "CAPS calls=~D points-per-path=~D colors=~D fields-per-color=~D"
            call-limit point-limit color-limit slot-count-limit)
      (if (and target (fboundp target))
          (let ((original (symbol-function target)))
            (setf (symbol-function target)
                  (lambda (&rest args)
                      (let* ((id (incf call-count))
                           (record-p (<= id call-limit))
                           (path (car args)))
                      (when (and (not record-p) (not overflow-written))
                        (setf overflow-written t)
                        (emit "OVERFLOW first-omitted-call=~D" id)
                        (unless end-written
                          (setf end-written t)
                          (emit "END natural-screen-color-data")))
                      (when record-p
                        (emit "CALL id=~D point-count-at-most=~D rplane=~S sdex=~S cdex=~S"
                              id (list-count-at-most path (1+ point-limit))
                              (state-token "RPLANE") (state-token "SDEX")
                              (state-token "CDEX"))
                        (when (= id 1) (emit-colors))
                        (map-points "before" id path))
                      (if record-p
                          (multiple-value-call
                              (lambda (&rest results)
                                (map-points "after" id path)
                                (emit "RETURN id=~D values=~S" id
                                      (mapcar #'safe-value results))
                                (values-list results))
                            (apply original args))
                        (apply original args)))))
            (emit "READY target=SCREEN-AND-STORE"))
        (emit "INSTALL-ERROR target=SCREEN-AND-STORE"))
      )
    (set 'aaron-natural-screen-color-capture-loaded t)))
