;;; Bounded natural SCREEN-AND-STORE path and writer-position observer.
;;; Load after the controlled writer-full trace and before normal scene startup.
(in-package :cl-user)

(unless (boundp 'aaron-natural-screen-unit-capture-loaded)
  (let* ((owner (find-package "COMMON-GRAPHICS-USER"))
         (target (and owner (find-symbol "SCREEN-AND-STORE" owner)))
         (tript (and owner (find-symbol "TRIPT" owner)))
         (twopt (and owner (find-symbol "TWOPT" owner)))
         (x (and owner (find-symbol "X" owner)))
         (y (and owner (find-symbol "Y" owner)))
         (report (open "C:\\temp\\aaron-screen-units.txt"
                       :direction :output :if-exists :supersede
                       :if-does-not-exist :create))
         (call-count 0)
         (call-limit 8)
         (point-limit 128)
         (overflow-written nil))
    (labels ((emit (control &rest arguments)
               (let ((*print-length* nil)
                     (*print-level* 10)
                     (*print-pretty* nil)
                     (*print-circle* t))
                 (apply #'format report control arguments)
                 (terpri report)
                 (finish-output report)))
             (typed (value)
               (if (numberp value)
                   (list :type (type-of value) :value value)
                 (list :type (type-of value))))
             (point (value)
               (handler-case
                   (if (and x y (or (and tript (typep value tript))
                                    (and twopt (typep value twopt)))
                            (fboundp x) (fboundp y))
                       (list :type (type-of value)
                             :x (typed (funcall (symbol-function x) value))
                             :y (typed (funcall (symbol-function y) value)))
                     (list :unexpected-type (type-of value)))
                 (condition (problem)
                   (list :point-error (type-of problem)))))
             (path-summary (value)
               (let ((rest value)
                     (items nil)
                     (count 0))
                 (do () ((or (null rest) (>= count point-limit)
                             (not (consp rest))))
                   (push (point (car rest)) items)
                   (setf rest (cdr rest))
                   (incf count))
                 (list :points (nreverse items)
                       :shown count
                       :truncated (and (consp rest) (>= count point-limit))
                       :proper (null rest)
                       :tail-type (when (and rest (not (consp rest)))
                                    (type-of rest)))))
             (binding (name)
               (handler-case
                   (let ((symbol (and owner (find-symbol name owner))))
                     (cond ((null symbol) (list :name name :missing t))
                           ((not (boundp symbol)) (list :name name :bound nil))
                           (t (list :name name :bound t
                                    :value (typed (symbol-value symbol))))))
                 (condition (problem)
                   (list :name name :error (type-of problem)))))
             (position ()
               (handler-case
                   (let ((symbol (and owner (find-symbol "*TEMP*" owner))))
                     (if (and symbol (boundp symbol)
                              (streamp (symbol-value symbol)))
                         (file-position (symbol-value symbol))
                       :unavailable))
                 (condition () :error)))
             (preview ()
               (handler-case
                   (let ((copy (make-random-state *random-state*)))
                     (list (random 100 copy)
                           (random 100 copy)
                           (random 100 copy)))
                 (condition () :error)))
             (state ()
               (list :position (position)
                     :rng (preview)
                     :rplane (binding "RPLANE")
                     :brush (binding "BRUSH")
                     :sdex (binding "SDEX")
                     :cdex (binding "CDEX"))))
      (emit "BEGIN natural-screen-unit v1")
      (emit "CAPS calls=~D points-per-path=~D" call-limit point-limit)
      (if (and target (fboundp target))
          (let ((original (symbol-function target)))
            (setf (symbol-function target)
                  (lambda (&rest args)
                    (let* ((id (incf call-count))
                           (record-p (<= id call-limit))
                           (path (car args)))
                      (when (and (not record-p) (not overflow-written))
                        (setf overflow-written t)
                        (emit "OVERFLOW first-omitted-call=~D" id))
                      (when record-p
                        (emit "CALL id=~D arg-count=~D path=~S other-args=~S before=~S"
                              id (length args) (path-summary path)
                              (mapcar #'typed (cdr args)) (state)))
                      (if (not record-p)
                          (apply original args)
                        (multiple-value-call
                            (lambda (&rest results)
                              (emit "RETURN id=~D values=~S path-after=~S after=~S"
                                    id (mapcar #'typed results)
                                    (path-summary path) (state))
                              (values-list results))
                          (apply original args))))))
            (emit "READY target=SCREEN-AND-STORE"))
        (emit "INSTALL-ERROR target=SCREEN-AND-STORE")))
    (set 'aaron-natural-screen-unit-capture-loaded t)))
