;;; Controlled point geometry calls, independent of scene/UI globals.
(in-package :cl-user)
(unless (boundp 'aaron-point-behavior-loaded)
  (set 'aaron-point-behavior-loaded t)
  (with-open-file (report "C:\\temp\\aaron-point-behavior.txt"
                          :direction :output :if-exists :supersede
                          :if-does-not-exist :create)
    (let ((*print-length* nil) (*print-level* 8) (*print-circle* nil)
          (*print-pretty* nil)
          (owner (find-package "COMMON-GRAPHICS-USER"))
          (factory (find-symbol "MAKE-RANDOM-STATE-FROM-SEED" "EXCL")))
      (labels ((call-point (name bounds)
                 (let ((a (apply (find-symbol "MAKE-TWOPT" owner) (car bounds)))
                       (b (apply (find-symbol "MAKE-TWOPT" owner) (cadr bounds))))
                   (funcall (find-symbol name owner) a b)))
               (coordinates (point)
                 (list (funcall (find-symbol "X" owner) point)
                       (funcall (find-symbol "Y" owner) point))))
        (format report "BEGIN point-behavior~%")
        (dolist (seed '(1 1234 5678 5489))
          (format report "GLOBAL ~S value=~D type=FIXNUM~%" "SEED" seed)
          (dolist (bounds '(((0 0) (10 0)) ((0 0) (0 10))
                            ((0 0) (-10 0)) ((0 0) (0 -10))
                            ((0 0) (10 10)) ((0 0) (-10 10))
                            ((0 0) (-10 -10)) ((0 0) (10 -10))
                            ((2 3) (12 8)) ((0 0) (0 0))
                            ((0.1f0 0.2f0) (0.3f0 0.4f0))
                            ((0.1d0 0.2d0) (0.3d0 0.4d0))))
            (let ((*random-state* (funcall factory seed)))
              (format report "TRY ~S args=~S~%" "XYDIST" bounds)
              (finish-output report)
              (handler-case
                  (format report "RESULT ~S values=(~S)~%" "XYDIST"
                          (call-point "XYDIST" bounds))
                (error (problem) (format report "ERROR ~S ~S~%" "XYDIST" (type-of problem))))
              (format report "TRY ~S args=~S~%" "LOCK-WIGGLE" bounds)
              (finish-output report)
              (handler-case
                  (let ((values nil))
                    (dotimes (i 4)
                      (push (coordinates (call-point "LOCK-WIGGLE" bounds)) values))
                    (format report "RESULT ~S values=~S~%" "LOCK-WIGGLE" (nreverse values)))
                (error (problem) (format report "ERROR ~S ~S~%" "LOCK-WIGGLE" (type-of problem))))
              (format report "TRY ~S args=(1000)~%" "RANDOM")
              (format report "RESULT ~S values=(~S)~%" "RANDOM" (random 1000))
              (finish-output report))))
        (format report "END point-behavior~%")
        (finish-output report)))))
