;;; Controlled point geometry calls, independent of scene/UI globals.
(in-package :cl-user)
(unless (boundp 'aaron-point-behavior-loaded)
  (set 'aaron-point-behavior-loaded t)
  (with-open-file (report "C:\\temp\\aaron-point-behavior.txt"
                          :direction :output :if-exists :supersede
                          :if-does-not-exist :create)
    (let ((*print-length* nil) (*print-level* 8) (*print-circle* nil)
          (*print-pretty* nil)
          (owner (find-package "COMMON-GRAPHICS-USER"))
          (factory (find-symbol "MAKE-RANDOM-STATE-FROM-SEED" "EXCL")))
      (labels ((call-point (name bounds)
                 (let ((a (apply (find-symbol "MAKE-TWOPT" owner) (car bounds)))
                       (b (apply (find-symbol "MAKE-TWOPT" owner) (cadr bounds))))
                   (funcall (find-symbol name owner) a b)))
               (coordinates (point)
                 (list (funcall (find-symbol "X" owner) point)
                       (funcall (find-symbol "Y" owner) point))))
        (format report "BEGIN point-behavior~%")
        ;; Resolve first-use dispatch before installing each measured state.
        ;; This warmup is excluded from the numeric observations below.
        (let ((*random-state* (funcall factory 1)))
          (mapcar #'coordinates (call-point "LOCK-WIGGLE" '((0 0) (10 0)))))
        (dolist (seed '(1 1234 5678 5489))
          (format report "GLOBAL ~S value=~D type=FIXNUM~%" "SEED" seed)
          (dolist (bounds '(((0 0) (10 0)) ((0 0) (0 10))
                            ((0 0) (-10 0)) ((0 0) (0 -10))
                            ((0 0) (10 10)) ((0 0) (-10 10))
                            ((0 0) (-10 -10)) ((0 0) (10 -10))
                            ((2 3) (12 8)) ((0 0) (0 0))
                            ((0.1f0 0.2f0) (0.3f0 0.4f0))
                            ((0.1d0 0.2d0) (0.3d0 0.4d0))
                            ((123.456f0 -78.125f0) (-32.875f0 0.0625f0))
                            ((123.456d0 -78.125d0) (-32.875d0 0.0625d0))
                            ((-0.00013f0 0.00027f0) (0.00031f0 -0.00019f0))
                            ((-0.00013d0 0.00027d0) (0.00031d0 -0.00019d0))
                            ((-91.3f0 -22.7f0) (-91.1f0 -22.9f0))
                            ((-91.3d0 -22.7d0) (-91.1d0 -22.9d0))
                            ((314.159f0 -271.828f0) (-161.803f0 141.421f0))
                            ((314.159d0 -271.828d0) (-161.803d0 141.421d0))))
            (let ((*random-state* (funcall factory seed)))
              (format report "TRY ~S args=~S~%" "XYDIST" bounds)
              (finish-output report)
              (handler-case
                  (format report "RESULT ~S values=(~S)~%" "XYDIST"
                          (call-point "XYDIST" bounds))
                (error (problem) (format report "ERROR ~S ~S~%" "XYDIST" (type-of problem))))
              (format report "TRY ~S args=~S~%" "LOCK-WIGGLE" bounds)
              (finish-output report)
              (handler-case
                  (let ((values nil))
                    (dotimes (i 4)
                      (push (mapcar #'coordinates (call-point "LOCK-WIGGLE" bounds)) values))
                    (format report "RESULT ~S values=~S~%" "LOCK-WIGGLE" (nreverse values)))
                (error (problem) (format report "ERROR ~S ~S~%" "LOCK-WIGGLE" (type-of problem))))
              (format report "TRY ~S args=(1000)~%" "RANDOM")
              (format report "RESULT ~S values=(~S)~%" "RANDOM" (random 1000))
              (finish-output report))))
        (format report "END point-behavior~%")
        (finish-output report)))))
