;;; Fresh states for floating RAN methods; trailing RANDOM measures consumption.
(in-package :cl-user)
(unless (boundp 'aaron-ran-float-loaded)
  (set 'aaron-ran-float-loaded t)
  (with-open-file (report "C:\\temp\\aaron-ran-float.txt"
                          :direction :output :if-exists :supersede
                          :if-does-not-exist :create)
    (let ((*print-length* nil) (*print-level* 6) (*print-circle* nil)
          (*print-pretty* nil)
          (factory (find-symbol "MAKE-RANDOM-STATE-FROM-SEED" "EXCL"))
          (ran (find-symbol "RAN" "COMMON-GRAPHICS-USER")))
      (format report "BEGIN ran-float~%")
      (dolist (seed '(1 1234 5678 5489))
        (format report "GLOBAL ~S value=~D type=FIXNUM~%" "SEED" seed)
        (dolist (bounds '((0.0f0 1.0f0) (0.0d0 1.0d0)
                          (0.0f0 10.0f0) (0.0d0 10.0d0)
                          (-2.5f0 4.75f0) (-2.5d0 4.75d0)
                          (-2.5f0 4.75d0) (-2.5d0 4.75f0)
                          (0.1f0 0.2f0) (0.1d0 0.2d0)
                          (0.1f0 0.2d0) (0.1d0 0.2f0)
                          (1.0f0 1.0f0) (1.0d0 1.0d0)
                          (10.0f0 0.0f0) (10.0d0 0.0d0)))
          (let ((*random-state* (funcall factory seed)))
            (format report "TRY ~S args=~S~%" "RAN" bounds)
            (finish-output report)
            (handler-case
                (let ((values nil))
                  (dotimes (i 8) (push (apply ran bounds) values))
                  (format report "RESULT ~S values=~S~%" "RAN" (nreverse values)))
              (error (problem) (format report "ERROR ~S ~S~%" "RAN" (type-of problem))))
            (format report "TRY ~S args=(1000)~%" "RANDOM")
            (format report "RESULT ~S values=(~S)~%" "RANDOM" (random 1000))
            (finish-output report))))
      (format report "END ran-float~%")
      (finish-output report))))
