;;; Natural row/neighbor observation plus an isolated local mask matrix.
;;; Original calls retain arguments, multiple values and error propagation.
;;; Direct slots only; maps are copied through typed displaced views.
(in-package :cl-user)

(unless (boundp 'aaron-scan-row-capture-loaded)
  (set 'aaron-scan-row-capture-loaded t)
  (let* ((owner (find-package "COMMON-GRAPHICS-USER"))
         (report (open "C:\\temp\\aaron-scan-row.txt" :direction :output
                       :if-exists :supersede :if-does-not-exist :create))
         (parents 0) (calls 0) (neighbors 0) (patches 0) (checks 0)
         (matrix-neighbors 0) (matrix-scans 0) (errors 0) (aborts 0) (overflow nil)
         (parent-stack nil) (current nil) (last-point nil) (last-scan 0) (last-count nil)
         (matrix-active nil) (saved-fill nil) (saved-patch nil)
         (scan-original (symbol-function (find-symbol "SCAN-ROW" owner)))
         (neighbor-original (symbol-function (find-symbol "NEIGHBORS" owner)))
         (dx '(1 1 0 -1 -1 -1 0 1)) (dy '(0 1 1 1 0 -1 -1 -1)))
    (labels
        ((emit (control &rest args)
           (when report
             (handler-case
                 (let ((*print-length* nil) (*print-level* nil) (*print-pretty* nil)
                       (*print-circle* nil) (*print-readably* nil))
                   (apply #'format report control args) (terpri report))
               (condition () (incf errors)))))
         (problem (phase condition)
           (incf errors)
           (emit "ERROR phase=~S type=~S message=~S" phase
                 (format nil "~S" (type-of condition)) (format nil "~A" condition)))
         (limit (kind amount)
           (setf overflow t) (emit "OVERFLOW kind=~S amount=~D" kind amount)
           (error "Scan observation cap"))
         (global (name)
           (let ((symbol (find-symbol name owner)))
             (unless (and symbol (boundp symbol)) (error "Missing binding ~A" name))
             (symbol-value symbol)))
         (point (object)
           (when object
             (let ((x (slot-value object (find-symbol "X" owner)))
                   (y (slot-value object (find-symbol "Y" owner)))
                   (z (slot-value object (find-symbol "Z" owner))))
               (unless (and (integerp x) (integerp y) (integerp z)) (error "Noninteger point"))
               (list (format nil "~S" (type-of object)) x y z))))
         (flat (map bits)
           (unless (and (arrayp map) (= (array-rank map) 2)
                        (equal (array-element-type map) (list 'unsigned-byte bits)))
             (error "Unexpected typed map"))
           (make-array (array-total-size map) :element-type (list 'unsigned-byte bits) :displaced-to map))
         (save-maps ()
           (let* ((fill (flat (global "FILL-MAP") 4)) (patch (flat (global "PATCH-MAP") 16)))
             (unless (and saved-fill (= (length saved-fill) (length fill))) (setf saved-fill (copy-seq fill)))
             (unless (and saved-patch (= (length saved-patch) (length patch))) (setf saved-patch (copy-seq patch)))
             (replace saved-fill fill) (replace saved-patch patch)))
         (map-equality (fill patch)
           (list (eq fill (global "FILL-MAP")) (eq patch (global "PATCH-MAP"))
                 (equalp saved-fill (flat (global "FILL-MAP") 4))
                 (equalp saved-patch (flat (global "PATCH-MAP") 16))))
         (rows (y)
           (let* ((map (global "PATCH-MAP")) (width (array-dimension map 0))
                  (height (array-dimension map 1)) (result nil))
             (unless (and (<= width 320) (<= height 480)) (limit :dimensions (* width height)))
             (dolist (row-y (list (1- y) y (1+ y)))
               (when (and (<= 0 row-y) (< row-y height))
                 (let ((runs nil) (value nil) (count 0))
                   (dotimes (x width)
                     (let ((next (aref map x row-y)))
                       (if (and (> count 0) (= next value)) (incf count)
                         (progn (when (> count 0) (push (list value count) runs))
                                (setf value next count 1)))))
                   (when (> count 0) (push (list value count) runs))
                   (push (list row-y (nreverse runs)) result))))
             (list width height (nreverse result))))
         (snapshot (phase thunk)
           (handler-case
               (let* ((preview (aaron-random-state-preview)) (result (funcall thunk)))
                 (unless (and (eq (car preview) :random-100-1)
                              (equal preview (aaron-random-state-preview)))
                   (error "Snapshot changed copied random preview"))
                 (incf checks) result)
             (condition (condition) (problem phase condition) nil)))
         (matrix ()
           (let* ((symbols (mapcar (lambda (name) (find-symbol name owner))
                                  '("PATCH-MAP" "*PIC-WIDE*" "*PIC-HIGH*")))
                  (preview (aaron-random-state-preview))
                  (original-values (mapcar #'symbol-value symbols))
                  (original-fill (global "FILL-MAP")) (original-patch (global "PATCH-MAP"))
                  (layout 0))
             (save-maps)
             (emit "MATRIX-BEGIN")
             (dolist (dimensions '((1 1) (1 3) (3 1) (2 2) (3 3) (5 5)))
               (let* ((width (first dimensions)) (height (second dimensions))
                      (map (make-array dimensions :element-type '(unsigned-byte 16) :initial-element 0))
                      (cells (make-array (* width height) :element-type '(unsigned-byte 16) :displaced-to map)))
                 (progv symbols (list map width height)
                   (dotimes (x width)
                     (dotimes (y height)
                       (when (or (< width 5) (and (member x '(0 2 4)) (member y '(0 2 4))))
                         (dolist (p '(0 7 65535))
                           (let ((other (if (= p 0) 9 0)))
                             (dotimes (center 2)
                               (dotimes (mask 256)
                                 (fill cells other) (setf (aref map x y) (if (= center 1) p other))
                                 (dotimes (d 8)
                                   (let ((nx (+ x (nth d dx))) (ny (+ y (nth d dy))))
                                     (when (and (<= 0 nx) (< nx width) (<= 0 ny) (< ny height)
                                                (logbitp d mask)) (setf (aref map nx ny) p))))
                                 (let* ((before (copy-seq cells))
                                        (values (multiple-value-list (funcall neighbor-original x y p))))
                                   (unless (and (= (length values) 1) (integerp (car values))
                                                (equalp cells before) (eq map (global "PATCH-MAP")))
                                     (error "Matrix neighbor mutated map or returned unsupported values"))
                                   (incf matrix-neighbors)
                                   (emit "MASK width=~D height=~D x=~D y=~D p=~D center=~D mask=~D value=~D"
                                         width height x y p center mask (car values)))))))))))))
             (let* ((width 5) (height 5)
                    (map (make-array '(5 5) :element-type '(unsigned-byte 16) :initial-element 0))
                    (cells (make-array 25 :element-type '(unsigned-byte 16) :displaced-to map)))
               (progv symbols (list map width height)
                 (dotimes (pattern 16)
                   (dolist (p '(0 7 65535))
                     (let ((other (if (= p 0) 9 0)))
                       (dotimes (x width)
                         (dotimes (y height)
                           (setf (aref map x y)
                                 (if (case pattern
                                       (0 nil) (1 t) (2 (= x 2)) (3 (= y 2))
                                       (4 (and (= x 2) (= y 2)))
                                       (5 (or (= x 0) (= x 4) (= y 0) (= y 4)))
                                       (6 (evenp (+ x y)))
                                       (t (< (mod (+ (* x 17) (* y 31) (* pattern 13) (* x y 7)) 11) 6)))
                                     p other))))
                       (incf layout) (emit "LAYOUT id=~D p=~D rows=~S" layout p
                                            (mapcar (lambda (y) (list y (second (assoc y (third (rows y)))))) '(0 1 2 3 4)))
                       (dotimes (row-index 6)
                         (let ((y (1- row-index)))
                           (dotimes (lx 6)
                             (dotimes (rx 6)
                               (let* ((before (copy-seq cells))
                                      (values (multiple-value-list (funcall scan-original lx rx y p))))
                                 (unless (and (= (length values) 1) (equalp before cells)
                                              (eq map (global "PATCH-MAP"))) (error "Matrix scan changed map or arity"))
                                 (incf matrix-scans)
                                 (emit "QUERY layout=~D lx=~D rx=~D y=~D p=~D point=~S"
                                       layout lx rx y p (point (car values)))))))))))))
             (unless (and (every #'eq original-values (mapcar #'symbol-value symbols))
                          (every #'identity (map-equality original-fill original-patch))
                          (eq (car preview) :random-100-1) (equal preview (aaron-random-state-preview)))
               (error "Matrix did not restore bindings/random preview"))
             (incf checks) (emit "MATRIX-END neighbors=~D scans=~D restored=T maps-same=T rng-same=T" matrix-neighbors matrix-scans)))
         (finish (status)
           (when (eq status :normal)
             (setf matrix-active t)
             (handler-case (matrix) (condition (condition) (problem :matrix condition)))
             (setf matrix-active nil))
           (emit "COMPLETE main=~S parents=~D scans=~D neighbors=~D patches=~D matrix-neighbors=~D matrix-scans=~D checks=~D errors=~D aborts=~D overflow=~S parent-depth=~D"
                 status parents calls neighbors patches matrix-neighbors matrix-scans checks errors aborts overflow (length parent-stack))
           (emit "END scan-row v2") (finish-output report) (close report) (setf report nil)))
      (emit "BEGIN scan-row v2")
      (emit "CAPS parents=250 scans=10000 neighbors=2000000 patches=1000")
      (emit "DIRECTIONS x=~S y=~S" (global "XINCS") (global "YINCS"))
      (unless (and (typep scan-original 'compiled-function) (typep neighbor-original 'compiled-function))
        (error "Expected original compiled row helpers"))
      (emit "TARGET name=~S type=~S" "SCAN-ROW" (format nil "~S" (type-of scan-original)))
      (emit "TARGET name=~S type=~S" "NEIGHBORS" (format nil "~S" (type-of neighbor-original)))
      (setf (symbol-function (find-symbol "NEIGHBORS" owner))
            (lambda (&rest args)
              (multiple-value-call
                  (lambda (&rest values)
                    (when (and report current (not matrix-active))
                      (incf neighbors) (when (> neighbors 2000000) (limit :neighbors neighbors))
                      (unless (and (= (length args) 3) (every #'integerp args)
                                   (= (length values) 1) (integerp (car values))) (error "Unsupported neighbor values"))
                      (push (append args values) (getf current :neighbors)))
                    (values-list values))
                (apply neighbor-original args))))
      (setf (symbol-function (find-symbol "SCAN-ROW" owner))
            (lambda (&rest args)
              (if (or (null report) matrix-active) (apply scan-original args)
                (let* ((id (incf calls)) (prior current) (completed nil)
                       (context (list :neighbors nil :flash nil)) (preview (aaron-random-state-preview))
                       (fill (global "FILL-MAP")) (patch (global "PATCH-MAP")))
                  (when (> calls 10000) (limit :scans calls))
                  (unless (and (= (length args) 4) (every #'integerp args)) (error "Unsupported scan arguments"))
                  (emit "SCAN id=~D parent=~D args=~S rows=~S" id (or (car parent-stack) 0) args
                        (snapshot :before (lambda () (save-maps) (rows (third args)))))
                  (setf current context)
                  (multiple-value-prog1
                    (unwind-protect
                      (multiple-value-call
                          (lambda (&rest values)
                            (unless (= (length values) 1) (error "Unsupported scan arity"))
                            (setf completed t last-point (car values) last-scan id)
                            (emit "RESULT id=~D point=~S neighbors=~S flash=~S map-equality=~S rng-same=~S" id
                                  (snapshot :after (lambda () (point (car values))))
                                  (nreverse (getf context :neighbors))
                                  (nreverse (getf context :flash))
                                  (snapshot :equality (lambda () (map-equality fill patch)))
                                  (equal preview (aaron-random-state-preview)))
                            (values-list values))
                        (apply scan-original args))
                    (unless completed (incf aborts) (emit "ABORT id=~D" id))
                    (setf current prior))
                    (when (zerop (mod id 128)) (finish-output report)))))))
      (let* ((symbol (find-symbol "FLASH-SPOT" owner)) (original (symbol-function symbol)))
        (setf (symbol-function symbol)
              (lambda (&rest args)
                (multiple-value-call
                    (lambda (&rest values)
                      (when (and report current (not matrix-active))
                        (unless (and (null args) (every (lambda (v) (or (null v) (integerp v))) values))
                          (error "Unsupported flash observation"))
                        (push (list args values) (getf current :flash)))
                      (values-list values))
                  (apply original args)))))
      (let* ((symbol (find-symbol "CFORM-COUNT" owner)) (original (symbol-function symbol)))
        (setf (symbol-function symbol)
              (lambda (&rest args)
                (multiple-value-call
                    (lambda (&rest values)
                      (when (and report parent-stack (not matrix-active))
                        (unless (and (= (length values) 1) (integerp (car values))) (error "Unsupported natural count"))
                        (setf last-count (car values)))
                      (values-list values))
                  (apply original args)))))
      (let* ((symbol (find-symbol "PATCH-EDGE" owner)) (original (symbol-function symbol)))
        (setf (symbol-function symbol)
              (lambda (&rest args)
                (when (and report (not matrix-active))
                  (incf patches) (when (> patches 1000) (limit :patches patches))
                  (emit "PATCH id=~D parent=~D scan=~D start=~S max=~D p=~D scan-result-eq=~S natural-count=~S"
                        patches (or (car parent-stack) 0) last-scan
                        (snapshot :patch (lambda () (point (first args))))
                        (second args) (third args) (eq (first args) last-point) last-count))
                (apply original args))))
      (let* ((symbol (find-symbol "BRUSH-FILL" owner)) (original (symbol-function symbol)))
        (setf (symbol-function symbol)
              (lambda (&rest args)
                (let ((id (incf parents)) (completed nil))
                  (when (> parents 250) (limit :parents parents))
                  (emit "PARENT id=~D args=~S" id args) (push id parent-stack)
                  (setf last-point nil last-scan 0 last-count nil)
                  (unwind-protect
                      (multiple-value-prog1 (apply original args) (setf completed t) (emit "END-PARENT id=~D" id))
                    (unless completed (incf aborts) (emit "ABORT-PARENT id=~D" id))
                    (pop parent-stack))))))
      (let* ((symbol (find-symbol "MAIN" owner)) (original (symbol-function symbol)))
        (setf (symbol-function symbol)
              (lambda (&rest args)
                (let ((completed nil))
                  (unwind-protect
                      (multiple-value-prog1 (apply original args) (setf completed t) (finish :normal))
                    (unless completed (finish :aborted)))))))
      (emit "READY") (finish-output report))))
