;;; Bounded constant-reference search, including generic methods and wrappers.
;;; A reference is a lead, not proof of a call edge. No drawing is invoked.
(in-package :cl-user)
(unless (boundp 'aaron-stroke-links-loaded)
  (set 'aaron-stroke-links-loaded t)
  (with-open-file (report "C:\\temp\\aaron-stroke-links.txt"
                          :direction :output :if-exists :supersede
                          :if-does-not-exist :create)
    (let* ((*print-length* nil) (*print-level* 10) (*print-circle* nil)
           (*print-pretty* nil) (owner (find-package "COMMON-GRAPHICS-USER"))
           (count-fn (find-symbol "FUNCTION-CONSTANT-COUNT" "EXCL"))
           (constant-fn (find-symbol "FUNCTION-CONSTANT" "EXCL"))
           (arglist (find-symbol "ARGLIST" "EXCL"))
           (methods (find-symbol "GENERIC-FUNCTION-METHODS" "CLOS"))
           (method-fn (find-symbol "METHOD-FUNCTION" "CLOS"))
           (targets (mapcar (lambda (name) (find-symbol name owner))
                           '("LOCK-WIGGLE" "HOP-OR-DRAW" "SCREEN-AND-STORE"
                             "STORE-IN-FILE" "PREP-LINE" "PARSE-HOP" "PARSE-P-HOP")))
           (names nil) (scanned 0) (failures 0) (hits 0))
      (labels ((summary (value)
                 (cond ((numberp value) (list :number value))
                       ((symbolp value) (list :symbol
                          (and (symbol-package value) (package-name (symbol-package value)))
                          (symbol-name value)))
                       ((stringp value) (list :string (subseq value 0 (min 160 (length value)))))
                       (t (list :type (type-of value)))))
               (scan (fn name origin depth)
                 (handler-case
                     (let ((count (funcall count-fn fn)) (values nil) (matched nil))
                       (incf scanned)
                       (when (and (integerp count) (<= 0 count 512))
                         (dotimes (i count)
                           (let ((value (funcall constant-fn fn i)))
                             (push value values)
                             (when (member value targets :test #'eq) (setf matched t))))
                         (setf values (nreverse values))
                         (when (or matched (member (find-symbol name owner) targets :test #'eq))
                           (incf hits)
                           (format report "MATCH ~S origin=~S depth=~D~%" name origin depth)
                           (format report "ARGLIST ~S~%" (funcall arglist fn))
                           (format report "CONSTANTS ~S~%" (mapcar #'summary values))
                           (finish-output report))
                         (when (< depth 2)
                           (do ((rest values (cdr rest)) (i 0 (1+ i))) ((null rest))
                             (when (typep (car rest) 'compiled-function)
                               (scan (car rest) name (list origin i) (1+ depth)))))))
                   (error () (incf failures)))))
        (format report "BEGIN stroke-links~%")
        (do-symbols (symbol owner)
          (when (and (eq owner (symbol-package symbol)) (fboundp symbol))
            (push (symbol-name symbol) names)))
        (setf names (sort names #'string<))
        (dolist (name names)
          (let ((fn (symbol-function (find-symbol name owner))))
            (if (eq (type-of fn) (find-symbol "STANDARD-GENERIC-FUNCTION" "COMMON-LISP"))
                (handler-case
                    (do ((rest (funcall methods fn) (cdr rest)) (i 0 (1+ i)))
                        ((or (null rest) (>= i 32)))
                      (scan (funcall method-fn (car rest)) name (list :method i) 0))
                  (error () (incf failures)))
              (scan fn name :direct 0))))
        (format report "SUMMARY names=~D scanned=~D hits=~D failures=~D~%"
                (length names) scanned hits failures)
        (format report "END stroke-links~%")
        (finish-output report)))))
