;;; Natural PATCH-EDGE / LIST-FRAME / MY-FILL(SUBFORM) boundaries.
;;; Full maps, direct point/frame slots, and only naturally invoked count readers.
;;; Original calls, multiple values and errors are preserved.
(in-package :cl-user)

(unless (boundp 'aaron-subform-boundary-capture-loaded)
  (set 'aaron-subform-boundary-capture-loaded t)
  (let* ((owner (find-package "COMMON-GRAPHICS-USER"))
         (report (open "C:\\temp\\aaron-subform-boundary.txt"
                       :direction :output :if-exists :supersede
                       :if-does-not-exist :create))
         (calls 0) (fills 0) (parents 0) (errors 0) (aborts 0) (overflow nil)
         (cells-total 0) (runs-total 0) (points-total 0) (checks 0)
         (stack nil) (parent-stack nil) (current nil) (last-outline nil) (last-frame nil)
         (input-fill nil) (input-patch nil) (input-fill-object nil) (input-patch-object nil)
         (counts (make-hash-table :test #'equal)))
    (labels
        ((emit (control &rest args)
           (when report
             (handler-case
                 (let ((*print-length* nil) (*print-level* nil) (*print-pretty* nil)
                       (*print-circle* nil) (*print-readably* nil))
                   (apply #'format report control args) (terpri report))
               (condition () (incf errors)))))
         (limit (kind amount)
           (setf overflow t) (emit "OVERFLOW kind=~S amount=~D" kind amount)
           (error "Subform boundary observation cap"))
         (problem (id phase condition)
           (incf errors)
           (emit "ERROR id=~D phase=~S type=~S message=~S" id phase
                 (format nil "~S" (type-of condition)) (format nil "~A" condition)))
         (global (name)
           (let ((symbol (find-symbol name owner)))
             (unless (and symbol (boundp symbol)) (error "Missing binding ~A" name))
             (symbol-value symbol)))
         (count-binding ()
           (let ((symbol (find-symbol "SUBP-COUNT" owner)))
             (if (and symbol (boundp symbol)) (symbol-value symbol) :unbound)))
         (slot (object name)
           (let ((value (slot-value object (find-symbol name owner))))
             (unless (integerp value) (error "Noninteger observed slot ~A" name)) value))
         (point (object)
           (list (format nil "~S" (type-of object))
                 (slot object "X") (slot object "Y") (slot object "Z")))
         (outline (value)
           (let ((rest value) (rows nil) (seen (make-hash-table :test #'eq)) (count 0))
             (do () ((not (consp rest)))
               (when (gethash rest seen) (error "Cyclic outline"))
               (setf (gethash rest seen) t)
               (when (>= count 10000) (limit :list-points count))
               (push (point (car rest)) rows) (incf count) (setf rest (cdr rest)))
             (unless (null rest) (error "Improper outline"))
             (incf points-total count)
             (when (> points-total 1000000) (limit :total-points points-total))
             (nreverse rows)))
         (frame (object)
           (list (format nil "~S" (type-of object))
                 (slot object "LX") (slot object "RX") (slot object "LY") (slot object "TY")))
         (map-snapshot (name bits)
           (let ((map (global name)))
             (unless (and (arrayp map) (= (array-rank map) 2)
                          (equal (array-element-type map) (list 'unsigned-byte bits)))
               (error "Unexpected map type"))
             (let* ((dimensions (array-dimensions map)) (width (first dimensions))
                    (height (second dimensions)) (cells (* width height)) (rows nil) (runs 0))
               (unless (and (> width 0) (> height 0) (<= cells 153600)) (limit :map-cells cells))
               (when (> (+ cells-total cells) 400000000) (limit :total-cells (+ cells-total cells)))
               (dotimes (y height)
                 (let ((row nil) (value nil) (count 0))
                   (dotimes (x width)
                     (let ((next (aref map x y)))
                       (if (and (> count 0) (= value next)) (incf count)
                         (progn
                           (when (> count 0) (push (list value count) row) (incf runs))
                           (setf value next count 1)))))
                   (when (> count 0) (push (list value count) row) (incf runs))
                   (push (list y :runs (nreverse row)) rows)))
               (incf cells-total cells) (incf runs-total runs)
               (when (> runs-total 10000000) (limit :map-runs runs-total))
               (list :type (format nil "~S" (type-of map)) :dimensions dimensions
                     :element-type (array-element-type map) :cells cells :covered cells
                     :runs runs :complete t :rows (nreverse rows)))))
         (maps ()
           (list :fill (map-snapshot "FILL-MAP" 4) :patch (map-snapshot "PATCH-MAP" 16)))
         (flat-map (name bits)
           (let ((map (global name)))
             (make-array (array-total-size map) :element-type (list 'unsigned-byte bits)
                         :displaced-to map)))
         (save-input-maps ()
           (setf input-fill-object (global "FILL-MAP") input-patch-object (global "PATCH-MAP")
                 input-fill (copy-seq (flat-map "FILL-MAP" 4))
                 input-patch (copy-seq (flat-map "PATCH-MAP" 16))))
         (input-equality ()
           (list :fill-identity (eq input-fill-object (global "FILL-MAP"))
                 :patch-identity (eq input-patch-object (global "PATCH-MAP"))
                 :fill-contents (equalp input-fill (flat-map "FILL-MAP" 4))
                 :patch-contents (equalp input-patch (flat-map "PATCH-MAP" 16))))
         (snapshot (id phase thunk)
           (handler-case
               (let* ((preview (aaron-random-state-preview)) (result (funcall thunk)))
                 (unless (and (eq (car preview) :random-100-1)
                              (equal preview (aaron-random-state-preview)))
                   (error "Observation changed copied random-state preview"))
                 (incf checks) result)
             (condition (condition) (problem id phase condition) nil)))
         (before (name args)
           (cond
             ((string= name "PATCH-EDGE")
              (unless (and (= (length args) 3) (integerp (second args)) (integerp (third args)))
                (error "Unexpected patch-edge arguments"))
              (save-input-maps)
              (list :start (point (first args)) :max (second args) :pdex (third args) :maps (maps)))
             ((string= name "LIST-FRAME")
              (unless (= (length args) 1) (error "Unexpected list-frame arguments"))
              (list :outline (outline (first args)) :out-list-eq (eq (first args) (global "OUT-LIST"))
                    :patch-result-eq (eq (first args) last-outline)))
             (t
              (list :outline (outline (global "OUT-LIST")) :frame (frame (global "SUB-FRAME"))
                    :patch-result-eq (eq (global "OUT-LIST") last-outline)
                    :frame-result-eq (eq (global "SUB-FRAME") last-frame)
                    :flag-bit (global "FLAG-BIT") :subp-count (count-binding)
                    :input-map-equality (input-equality)))))
         (after (name args values context)
           (cond
             ((string= name "PATCH-EDGE")
              (unless (= (length values) 1) (error "Unexpected patch-edge values"))
              (setf last-outline (car values))
              (list :outline (outline (car values)) :start (point (first args))
                    :input-map-equality (input-equality)))
             ((string= name "LIST-FRAME")
              (unless (= (length values) 1) (error "Unexpected list-frame values"))
              (setf last-frame (car values))
              (list :frame (frame (car values)) :outline (outline (first args))
                    :out-list-eq (eq (first args) (global "OUT-LIST"))))
             (t
              (unless (every (lambda (v) (or (null v) (integerp v))) values)
                (error "Unexpected MY-FILL values"))
              (list :values values :outline (outline (global "OUT-LIST"))
                    :frame (frame (global "SUB-FRAME")) :subp-count (global "SUBP-COUNT")
                    :readers (nreverse (getf context :readers)) :maps (maps)))))
         (install-reader (name)
           (let* ((symbol (find-symbol name owner)) (original (symbol-function symbol)))
             (emit "INSTALL name=~S type=~S" name (format nil "~S" (type-of original)))
             (setf (symbol-function symbol)
                   (lambda (&rest args)
                     (multiple-value-call
                         (lambda (&rest values)
                           (when (and current (string= (getf current :name) "MY-FILL"))
                             (handler-case
                                 (progn
                                   (unless (and (= (length args) 1) (= (length values) 1)
                                                (integerp (car values))) (error "Unexpected natural reader"))
                                   (push (list name (car values)) (getf current :readers)))
                               (condition (condition) (problem (getf current :id) name condition))))
                           (values-list values))
                       (apply original args))))))
         (install-target (name)
           (let* ((symbol (find-symbol name owner)) (original (symbol-function symbol)))
             (emit "INSTALL name=~S type=~S" name (format nil "~S" (type-of original)))
             (setf (symbol-function symbol)
                   (lambda (&rest args)
                     (let ((fill-id nil))
                       (when (and report (string= name "MY-FILL"))
                         (setf fill-id (incf fills))
                         (emit "FILL id=~D parent=~D mode=~S cdex=~D sdex=~D" fill-id
                               (or (car parent-stack) 0) (symbol-name (first args)) (second args) (third args)))
                       (if (or (null report) overflow
                               (and (not (string= name "MY-FILL")) (null parent-stack))
                               (and (string= name "MY-FILL") (not (string= (symbol-name (first args)) "SUBFORM"))))
                           (apply original args)
                         (let* ((id (incf calls)) (prior current) (completed nil)
                                (context (list :id id :name name :readers nil))
                                (fill-map (global "FILL-MAP")) (patch-map (global "PATCH-MAP")))
                           (when (> calls 1000) (limit :calls calls))
                           (incf (gethash name counts 0)) (push id stack)
                           (emit "CALL id=~D parent=~D fill=~D name=~S before=~S" id (or (car parent-stack) 0)
                                 (or fill-id 0) name (snapshot id :before (lambda () (before name args))))
                           (setf current context)
                           (unwind-protect
                               (multiple-value-call
                                   (lambda (&rest values)
                                     (setf completed t)
                                     (emit "RETURN id=~D after=~S map-identities=~S" id
                                           (snapshot id :after (lambda () (after name args values context)))
                                           (list (eq fill-map (global "FILL-MAP")) (eq patch-map (global "PATCH-MAP"))))
                                     (values-list values))
                                 (apply original args))
                             (unless completed (incf aborts) (emit "ABORT id=~D" id))
                             (pop stack) (setf current prior)))))))))
         (install-parent ()
           (let* ((symbol (find-symbol "BRUSH-FILL" owner)) (original (symbol-function symbol)))
             (emit "INSTALL name=~S type=~S" "BRUSH-FILL" (format nil "~S" (type-of original)))
             (setf (symbol-function symbol)
                   (lambda (&rest args)
                     (let ((id (incf parents)) (completed nil))
                       (when (> parents 250) (limit :parents parents))
                       (emit "PARENT id=~D args=~S" id args) (push id parent-stack)
                       (setf last-outline nil last-frame nil)
                       (unwind-protect
                           (multiple-value-prog1 (apply original args)
                             (setf completed t) (emit "END-PARENT id=~D" id))
                         (unless completed (incf aborts) (emit "ABORT-PARENT id=~D" id))
                         (pop parent-stack)))))))
         (finish (status)
           (dolist (name '("PATCH-EDGE" "LIST-FRAME" "MY-FILL"))
             (emit "TOTAL name=~S calls=~D" name (gethash name counts 0)))
           (emit "COMPLETE main=~S calls=~D fills=~D parents=~D points=~D cells=~D runs=~D checks=~D errors=~D aborts=~D overflow=~S depth=~D parent-depth=~D"
                 status calls fills parents points-total cells-total runs-total checks errors aborts overflow
                 (length stack) (length parent-stack))
           (emit "END subform-boundary v3")
           (when report (finish-output report) (close report) (setf report nil))))
      (emit "BEGIN subform-boundary v3")
      (emit "CAPS calls=1000 parents=250 list-points=10000 total-points=1000000 map-cells=153600 total-cells=400000000 map-runs=10000000")
      (emit "DIRECTIONS xincs=~S yincs=~S" (global "XINCS") (global "YINCS"))
      (dolist (name '("PATCHDEX" "CFORM-COUNT")) (install-reader name))
      (dolist (name '("PATCH-EDGE" "LIST-FRAME" "MY-FILL")) (install-target name))
      (install-parent)
      (let* ((symbol (find-symbol "MAIN" owner)) (original (symbol-function symbol)))
        (emit "INSTALL name=~S type=~S" "MAIN" (format nil "~S" (type-of original)))
        (setf (symbol-function symbol)
              (lambda (&rest args)
                (let ((completed nil))
                  (unwind-protect
                      (multiple-value-prog1 (apply original args) (setf completed t) (finish :normal))
                    (unless completed (finish :aborted)))))))
      (emit "READY") (finish-output report))))
