;;; Original native metadata for SUBFORM boundary construction candidates.
;;; No application routines are invoked or replaced.
(in-package :cl-user)

(unless (boundp 'aaron-subform-boundary-native-links-loaded)
  (set 'aaron-subform-boundary-native-links-loaded t)
  (with-open-file (report "C:\\temp\\aaron-subform-boundary-native-links.txt"
                          :direction :output :if-exists :supersede
                          :if-does-not-exist :create)
    (let* ((*print-length* nil) (*print-level* 8) (*print-pretty* nil)
           (*print-readably* nil) (*print-circle* nil)
           (owner (find-package "COMMON-GRAPHICS-USER"))
           (count-helper (find-symbol "FUNCTION-CONSTANT-COUNT" "EXCL"))
           (constant-helper (find-symbol "FUNCTION-CONSTANT" "EXCL"))
           (arglist (find-symbol "ARGLIST" "EXCL"))
           (memref (find-symbol "MEMREF" "SYSTEM")))
      (format report "BEGIN subform-boundary-native-links~%")
      (dolist (name '("PATCH-EDGE" "LIST-FRAME" "NEIGHBORS"))
        (let* ((symbol (find-symbol name owner))
               (fn (and symbol (fboundp symbol) (symbol-function symbol))))
          (unless (and fn (typep fn 'compiled-function))
            (error "Expected original compiled function ~A" name))
          (format report "FUNCTION name=~S type=~S~%" name (type-of fn))
          (format report "ARGLIST name=~S values=~S~%" name
                  (multiple-value-list (funcall arglist symbol)))
          (format report "HEADER name=~S bytes=" name)
          (dotimes (i 64)
            (format report "~2,'0X" (funcall memref fn 0 i :unsigned-byte)))
          (terpri report)
          (let ((count (funcall count-helper fn)))
            (unless (and (integerp count) (<= 0 count 4096))
              (error "Unexpected constant count for ~A" name))
            (format report "CONSTANT-COUNT name=~S count=~D~%" name count)
            (dotimes (i count)
              (let ((value (funcall constant-helper fn i)))
                (format report "CONSTANT name=~S index=~D value=~S~%"
                        name i
                        (cond ((symbolp value)
                               (list :symbol (and (symbol-package value)
                                                  (package-name (symbol-package value)))
                                     (symbol-name value)))
                              ((numberp value) (list :number value))
                              (t (list :type (type-of value))))))))
          (finish-output report)))
      (format report "TARGET-COUNT 3~%ERROR-COUNT 0~%END subform-boundary-native-links~%")
      (finish-output report)))
  (when (and (boundp 'aaron-pre-scene-probe-pause-seconds)
             (> aaron-pre-scene-probe-pause-seconds 0))
    (let ((released nil))
      (dotimes (i (* 10 aaron-pre-scene-probe-pause-seconds))
        (when (probe-file "C:\\temp\\aaron-native-code-release.txt")
          (setf released t)
          (return))
        (sleep 0.1))
      (unless released (error "Native capture parent did not release the probe")))))
